### ISSUE TITLE
Synergy support

### ISSUE THREAD

**Issue by josephlavin** [RedBearAK/toshy#106]
I am following up on https://github.com/rbreaves/kinto/issues/835.

Synergy customer service suggested watching the synergy log file for these entries:

```
INFO    - leaving screen
INFO    - entering screen
```

Then triggering the enable/disable actions when those entries are added.

I could do this w/ an external script as I am guessing nothing like that exists w/ Kinto or Toshy.   I am up for some back and forth if you have any other ideas ;)

**Comment by RedBearAK** [comment]
@josephlavin 

Hey, thanks for responding on this, and with such useful info. 

> could do this w/ an external script as I am guessing nothing like that exists w/ Kinto or Toshy

Well, for Kinto, no. But for Toshy... it's kinda "fancied up" compared to Kinto. It uses a Python package called `watchdog` to monitor an sqlite3 database file for changes, to modify some preferences without needing to restart the keymapper process. They just change the value of some variables in memory and modify how some keymapping conditionals evaluate, so some behaviors of the config can be changed "live". 

Something similar or just a thread or external script that follows the output of the log file could probably be implemented to disable the modmapping like Kinto does for "remotes". 

Right now an external script would need to probably disable the `xkeysnail` service with Kinto, and then restart it when you return from Synergy, but that always takes a few seconds. There's always a minor risk that holding down a mod key at the wrong time during the keymapper startup will cause it to get stuck in an inconsistent state that may prevent the use of the keyboard, or cause it to act really weird until you can kill or restart the keymapper process. And then there is the problem that on X11 there is a limitation in how keymapping works, that requires tapping a modifier key once before any combos actually work correctly. (This isn't an issue on Wayland.) So you would run into this and need to be tapping a modifier key literally every time you left Synergy, after waiting about 5 seconds for the keymapper to restart. 

Let me look at what would be involved in monitoring the log file. Where exactly is the Synergy log file located, under what name?

**Comment by josephlavin** [comment]
For me (running Synergy RC3) the log is located at `~/.local/state/Synergy/synergy.log`.  Though I think it may be different for older versions (`/var/log/synergy/` according to [this](https://forums.symless.com/topic/3207-synergy-2-how-to-send-your-log-links/)).

And here is what I'm seeing:
```
synergy-core    [2023-11-08T11:04:30] - INFO    - entering screen
synergy-core    [2023-11-08T11:19:54] - INFO    - switch from "popos-76ce5319" to "macbookprointel-a593971a" at 1933,0
synergy-core    [2023-11-08T11:19:54] - INFO    - leaving screen
synergy-core    [2023-11-08T11:19:54] - INFO    - screen "popos-76ce5319" updated clipboard 1
synergy-core    [2023-11-08T11:19:57] - INFO    - switch from "macbookprointel-a593971a" to "popos-76ce5319" at 2827,3378
synergy-core    [2023-11-08T11:19:57] - INFO    - entering screen
synergy-core    [2023-11-08T12:08:34] - INFO    - switch from "popos-76ce5319" to "macbookprointel-a593971a" at 759,0
synergy-core    [2023-11-08T12:08:34] - INFO    - leaving screen
synergy-core    [2023-11-08T12:08:34] - INFO    - screen "popos-76ce5319" updated clipboard 0
synergy-core    [2023-11-08T12:08:34] - INFO    - screen "popos-76ce5319" updated clipboard 1
synergy-core    [2023-11-08T12:08:35] - INFO    - switch from "macbookprointel-a593971a" to "popos-76ce5319" at 4535,3444
synergy-core    [2023-11-08T12:08:35] - INFO    - entering screen
```

Seems like the `leaving screen` entry is when I'm on the host leaving.  And `entering screen` is when I come back.

And I concluded for Kinto the `xkeysnail` service would need to be disabled/enabled on the fly as well.

**Comment by RedBearAK** [comment]
Awesome, thanks for the info. 

From initially looking into this, most likely it would be possible to just add a second path for the `watchdog` observer to monitor for changes, and then pull the most recent lines and try to match on those patterns and flip a state variable in the config file that could be added to the modmaps and disable them whenever there is a "leaving screen" and no "entering screen". There will probably be a lot of implementation details to make it as reliable as possible, however. Like, making sure Synergy is actually running and not letting the keymapper config get stuck in the disabled mode if the user quits Synergy (or it crashes) before it logs an "entering screen". Things like that. 

As far as I understand, the keymapper doesn't get disabled, so technically everything continues to pass through the keymapper, but when you are in a "remotes" app the Kinto config would disable the modmaps that move the modifier key locations, and the "general" keymap that would affect all apps. So you end up in a state where the keymapper behaves as if it doesn't need to do any remapping while in the "remotes" group of apps. This is what Toshy inherited from Kinto. 

So in theory if we can just add a state variable like `SYNERGY_OFFSCREEN` to those same modmaps and keymaps that turn themselves off in "remotes" (like VNC/RDP apps), the same thing can apply to when the cursor is on the remote Synergy screen. Not exactly the same as literally stopping the keymapper process, but much less intrusive/faster. 

Is Synergy compatible with Wayland now? I wonder if the situation with the missing class/name/title window info is the same in Wayland.

**Comment by RedBearAK** [comment]
It could be instructive if you were to run Toshy in a Wayland session (GNOME, KDE Plasma, or sway) and look at the verbose logging while moving the focus to the Synergy screen and trying some kind of general shortcut like Cmd+Shift+Left_Brace (bracket). This would leave evidence in the log for what the keymapper is seeing for the app class and window name/title for Synergy while in Wayland. 

In order to do this you'd need to disable Kinto's auto-start option and stop Kinto, which can be done either from Kinto's tray icon menu or the Kinto GUI app menu. Otherwise there would be a conflict over the `/dev/uinput` device between the two apps. 

To return to Kinto after installing and using Toshy, you can run the `toshy-services-disable` command in a terminal, and then `toshy-services-stop` (or use the tray icon menu to stop the services). The disable command will prevent the Toshy services from auto-starting. Of course you can also do a full uninstall using the same `setup_toshy.py` script you use to install. 

So they can both be installed at the same time, you just need to make sure only one actually starts when you boot up and log in to your desktop. Toshy only runs when you log in to a desktop, where Kinto uses a system service that runs prior to logging in to a desktop. 

If you do install Toshy, the first install will normally need to ask you to reboot, in order to get some group permissions and a `udev` rule in place/working.

**Comment by josephlavin** [comment]
Hello!  Thank you for the response. That is a lot to consider in the context of Toshy (and Kinto).  I thought I would try a simple script running locally just to see if I watching the log file and enabling / disabling the service works.  So far it is working but time will tell if any edge cases exists.  (I think it has an issue when you have something in the clipboard) I have not had the opportunity to switch over to Toshy (however I want too) so the script is built for Kinto.

```bash
#!/bin/bash

# Watch the Synergy log file to:
# stop xkeysnail when leaving screen
# start xkeysnail when entering screen

log=~/.local/state/Synergy/synergy.log

last_line=$(tail -1 $log)

while : ; do
    sleep 0.25

    line=$(tail -1 $log)

    if [[ "$last_line" != "$line" ]]; then
        # echo "evaluating line: $line"

        # Going to remote desktop
        if [[ "$line" == *"leaving screen" ]]; then
            echo "Leaving screen: Stopping xkeysnail"
            sudo systemctl stop xkeysnail
        fi

        # Returning to this desktop
        if [[ "$line" == *"entering screen" ]]; then
            echo "Returning to screen: Starting xkeysnail"
            sudo systemctl start xkeysnail
        fi
    fi

    last_line=$line
done
```

Ideally (as you said) it would be great not to kill the service but just stop all remapping. That would be faster and most likely more reliable.  Can that be done via. a bash script with Toshy (for a more refined proof of concept script that works w/ Toshy)?

**Comment by RedBearAK** [comment]
> Can that be done via. a bash script with Toshy

What we would want to do with Toshy is just have it watch the Synergy log file in almost the same way it is already watching for changes in an sqlite3 database file that contains preferences. It does this so that when you change a preference from the icon or GUI app, the config can start acting differently right away, without needing to restart anything. 

So it could be as simple as setting the "general" modmaps and keymaps to have a new variable in the conditional statement, that could just be toggled on and off. 

The config is already set up so that if you are in an app that is part of the "remotes" group, like Remmina, AnyDesk, anything where you want the keymapping to stop, those modmaps and the "general" keymaps will just disable themselves. So the same kind of thing can work for Synergy, just having the config file toggle a variable within itself. 

The only problem with running polling loops like that is when you start getting into wanting it to react very quickly (like your 0.25 seconds in the bash script) it can start using up a lot of CPU cycles relative to everything else on the system. 

But doing this from inside the Python module with `watchdog` should be more efficient than using an external Bash script. In theory `watchdog` would only initiate the reading of the last line of the file when it detects that the file has been modified.

**Comment by RedBearAK** [comment]
@josephlavin 

Switch to the `dev_beta` branch and install from the zip you get from the `Code` button, and in theory the Toshy config will watch the Synergy log (if it exists) and immediately disable/enable all keymaps/modmaps in the keymapper config that use the `matchProps` function. Which is basically everything, especially all the "general" keymaps and modmaps that mainly check to see whether you are in some app in the "remotes" group. So as soon as Synergy writes the info to the log, the watchdog observer should read out the last little bit of the log and set the state of the keymapper, and it should happen pretty quickly. 

It is working in my testing, where I just echoed the trigger patterns into a fake log file, since I don't use Synergy and don't have a multi-monitor setup right now to play with it for real. But it should work exactly the same way with the real log file. 

Remember to disable Kinto and its auto-start option if you still have it installed. And the `toshy-services-stop` and `toshy-services-disable` commands will let you stop Toshy and keep it from auto-starting if you want to switch back to Kinto. 

There is a small risk of the keymapper getting "stuck" in the disabled state, if Synergy never writes the "entering screen" line to the log before exiting/crashing. If that seems to happen, just restart the Toshy services and it should start working again. The risk of this should be pretty small if Synergy doesn't have a habit of crashing, and it would need to have the focus when that happens, or the last relevant line in the log would still be "entering screen", which would leave the keymapper enabled. 

Let me know if you get a chance to test this.

**Comment by josephlavin** [comment]
@RedBearAK
I finally got some time to sit down, install Toshy and test this out.  Once I got it up and running: it seems to be working great!  I'll keep it running and let you know how stable it appears to be.

I can't thank you enough for implementing this feature!  I was going to give it a shot but Phython is not a language I know ;)

**Comment by RedBearAK** [comment]
@josephlavin 

> seems to be working great! I'll keep it running and let you know how stable it appears to be.

Yes, I'm very interested in how well this seems to work long term. Once in testing I had a strange delay happening on all typing, which was abnormal and I have no idea why that was happening. Restarting Toshy fixed it. There's a throttle delay by default in the Toshy config, but that is supposed to only provide a time buffer around the use of modifier keys, so that macros and Unicode sequences work correctly. There should be no detectable delay with "normal" key presses. 

Due to the default throttle delays you may feel like it's necessary to be more deliberate with using the Shift key, or it may fail to produce the Shifted character. If you feel like this is a problem you can experiment with reducing the throttle delays in the config file. There's a special shortcut documented in the README that will emit a test macro into any kind of text editor, to reveal whether your system can handle the shorter throttle delays without screwing up macros/Unicode sequences. 

Python is a remarkably simple language. Very easy to get yourself in lots of trouble in seconds flat. 👍🏽 

Still a beginner myself, really.

**Comment by RedBearAK** [comment]
Closing this as completed. Open a new issue if there is a problem related to Synergy.

**Comment by josephlavin** [comment]
@RedBearAK: Just wanted to let you know that I have been running this for a couple of weeks now.  It is working great w/ no issues so far.  Thanks again!

**Comment by RedBearAK** [comment]
@josephlavin 

I really appreciate you giving it a good run, and taking the time to come back and leave a note. Hearing that nothing obvious is going wrong is reassuring. Thanks! 👍🏽
