### ISSUE TITLE
[BUG] Ctrl+` not working in Visual Studio Code

### ISSUE THREAD

**Issue by fervidnerd** [RedBearAK/toshy#110]
```
Bare metal or virtual machine: 
(If in VM, which VM software): None

(Try running 'toshy-env' in a terminal.)

Linux distro name: Ubuntu
Distro version: 22.04
X11/Xorg or Wayland: Wayland 
Desktop environment(s): Gnome 42.9

Any DE(s) tried with Wayland?: 

Keyboard type (IBM, Chromebook, Windows, Apple):  Apple
Keyboard device name (try 'toshy-devices'): Apple Inc. Apple Internal Keyboard / Trackpad
```

```
Current status of Toshy systemd services...
--------------------------------------------------------------------------------
○ toshy-kde-dbus.service - Toshy KDE D-Bus Service
     Loaded: loaded (/home/harry/.config/systemd/user/toshy-kde-dbus.service; enabled; vendor preset: enabled)
     Active: inactive (dead) since Wed 2023-11-22 09:41:03 EET; 7min ago
    Process: 74985 ExecStartPre=/bin/bash -c if [ -z "$XDG_SESSION_TYPE" ]; then sleep 3; exit 1; fi (code=exited, status=0/SUCCESS)
    Process: 74986 ExecStart=/bin/bash -c env TERM=xterm $HOME/.config/toshy/scripts/bin/toshy-kde-dbus-service.sh (code=exited, status=0/SUCCESS)
   Main PID: 74986 (code=exited, status=0/SUCCESS)
        CPU: 232ms

Nov 22 09:41:00 harry-ubuntu systemd[1761]: Starting Toshy KDE D-Bus Service...
Nov 22 09:41:00 harry-ubuntu systemd[1761]: Started Toshy KDE D-Bus Service.
Hint: Some lines were ellipsized, use -l to show in full.
--------------------------------------------------------------------------------
● toshy-session-monitor.service - Toshy Session Monitor
     Loaded: loaded (/home/harry/.config/systemd/user/toshy-session-monitor.service; enabled; vendor preset: enabled)
     Active: active (running) since Wed 2023-11-22 09:41:02 EET; 7min ago
   Main PID: 75044 (bash)
      Tasks: 2 (limit: 18981)
     Memory: 576.0K
        CPU: 6.186s
     CGroup: /user.slice/user-1000.slice/user@1000.service/app.slice/toshy-session-monitor.service
             ├─75044 bash /home/harry/.config/toshy/scripts/toshy-service-sessi…
             └─78472 sleep 2

Nov 22 09:41:02 harry-ubuntu systemd[1761]: Started Toshy Session Monitor.
--------------------------------------------------------------------------------
● toshy-config.service - Toshy Config Service
     Loaded: loaded (/home/harry/.config/systemd/user/toshy-config.service; enabled; vendor preset: enabled)
     Active: active (running) since Wed 2023-11-22 09:41:48 EET; 6min ago
    Process: 75499 ExecStartPre=/bin/bash -c env TERM=xterm $HOME/.config/toshy/scripts/toshy-service-config-execstartpre.sh (code=exited, status=0/SUCCESS)
   Main PID: 75501 (bash)
      Tasks: 6 (limit: 18981)
     Memory: 20.2M
        CPU: 14.451s
     CGroup: /user.slice/user-1000.slice/user@1000.service/app.slice/toshy-config.service
             ├─75501 bash /home/harry/.config/toshy/scripts/toshy-service-confi…
             └─75504 /home/harry/.config/toshy/.venv/bin/python /home/harry/.co…

Nov 22 09:41:48 harry-ubuntu systemd[1761]: Starting Toshy Config Service...
Nov 22 09:41:48 harry-ubuntu systemd[1761]: Started Toshy Config Service.
--------------------------------------------------------------------------------
Use 'toshy-services-disable' to disable Toshy services autostart at login.
Use 'toshy-services-enable' to (re)enable Toshy services autostart at login.
Use 'toshy-systemd-remove' to uninstall/remove Toshy services.
Use 'toshy-systemd-setup' to install/reinstall Toshy services.
```

```
List of devices seen by the keymapper (keyszer): 

keyszer v0.7.1
------------------------------------------------------------------------------------
Device               Name                                Phys
------------------------------------------------------------------------------------
/dev/input/event0    Lid Switch                          PNP0C0D/button/input0
/dev/input/event1    Power Button                        PNP0C0C/button/input0
/dev/input/event2    Sleep Button                        PNP0C0E/button/input0
/dev/input/event3    Power Button                        LNXPWRBN/button/input0
/dev/input/event4    Apple Inc. Apple Internal Keyboard / Trackpad
                                                         usb-0000:00:14.0-12/input0
/dev/input/event7    bcm5974                             usb-0000:00:14.0-12/input0
/dev/input/event8    HDA Intel PCH Mic                   ALSA
/dev/input/event9    HDA Intel PCH Headphone             ALSA
/dev/input/event10   HDA Intel PCH SPDIF                 ALSA
/dev/input/event11   Video Bus                           LNXVIDEO/video/input0
/dev/input/event5    HDA Intel HDMI HDMI/DP,pcm=3        ALSA
/dev/input/event6    HDA Intel HDMI HDMI/DP,pcm=7        ALSA
/dev/input/event12   HDA Intel HDMI HDMI/DP,pcm=8        ALSA
/dev/input/event13   Keyszer (virtual) Keyboard          py-evdev-uinput
```

```
(EV) Toshy env module sees this environment:
		 DISTRO_NAME     = 'ubuntu'
		 DISTRO_VER      = '22.04'
		 VARIANT_ID      = 'notfound'
		 SESSION_TYPE    = 'wayland'
		 DESKTOP_ENV     = 'gnome'
		 DE_MAJ_VER      = '42'
```

Problem observed:  
```Ctrl+` should open the integrated terminal in visual studio code. Instead it just prints the character '`'```

**Comment by RedBearAK** [comment]
@fervidnerd 

Definitely works for the terminal on VSCode on macOS. My issue with in-app window switching was due to a stray Super+Grave shortcut in GNOME. 

The " ` " key is typically referred to as Grave, the accent character that leans the opposite direction of Acute. 

To open your Toshy config folder and get to the config file, there is a convenient option on the tray icon menu (`Open Config Folder`) near the bottom of the menu. The folder is at `~/.config/toshy` if you want to get there some other way. 

Open the `toshy_config.py` file in some kind of text editor and find the `VSCodes` keymap. Add the extra line you see here, for Super+Grave to remap to Ctrl+J: 

```py
keymap("VSCodes", {
    # C("Super-Space"):           C("LC-Space"),                  # Basic code completion (conflicts with input switching)

    # Override the global Cmd+Dot (Escape/cancel) shortcut for QuickFix in VSCode(s)
    C("RC-Dot"):                C("RC-Dot"),                    # QuickFix, overriding global shortcut

    C("Super-Grave"):           C("C-j"),                       # Open terminal (Cmd+J also works)

    # Find dialog options
    C("Alt-RC-C"):              C("Alt-C"),                     # Find: toggle "Match Case"
    C("Alt-RC-W"):              C("Alt-W"),                     # Find: toggle "Match Whole Word"
    C("Alt-RC-R"):              C("Alt-R"),                     # Find: toggle "Use Regular Expression"
    C("Alt-RC-L"):              C("Alt-L"),                     # Find: toggle "Find in Selection"
    C("Alt-RC-P"):              C("Alt-P"),                     # Replace: toggle "Preserve Case"
```

This might seem odd, but the physical Ctrl key gets the Super/Meta/Win/Cmd key code when you are in a GUI app like VSCode. This remap seems to work for me, just like the Cmd+J shortcut that I've been using for a long time. I didn't realize there was another shortcut to open the terminal. 

Save the file after you make the edit, then restart Toshy with whichever method you prefer: The tray icon menu (`(Re)Start Toshy Services`) or the GUI preferences app, or the terminal command `toshy-services-restart`. Toshy doesn't need to be restarted if you just change preferences from the tray icon menu or Preferences app, but if you make any change to the config file the keymapper has to be restarted. 

If you can confirm this works for you and does what you want, I'll add this remap to the default Toshy config file so you won't have this issue again if you ever need to reinstall Toshy or install it on another machine (or user account). 

Thanks for the bug report. 👍🏽

**Comment by RedBearAK** [comment]
@fervidnerd 

Merged this into the default Toshy config file. You shouldn't have this issue with future installs or re-installs. 

Feel free to close this issue when you confirm the fix works for you.

**Comment by mrbrownt** [comment]
I tried the current version of main and \` + ctl works for toggling the terminal, but \` + shift + ctl is triggering window switching instead of creating a new terminal in vscode.

**Comment by fervidnerd** [comment]
> @fervidnerd
> 
> Definitely works for the terminal on VSCode on macOS. My issue with in-app window switching was due to a stray Super+Grave shortcut in GNOME.
> 
> The " ` " key is typically referred to as Grave, the accent character that leans the opposite direction of Acute.
> 
> To open your Toshy config folder and get to the config file, there is a convenient option on the tray icon menu (`Open Config Folder`) near the bottom of the menu. The folder is at `~/.config/toshy` if you want to get there some other way.
> 
> Open the `toshy_config.py` file in any kind of text editor and find the `VSCodes` keymap. Add the extra line you see here, for Super+Grave to remap to Ctrl+J:
> 
> ```python
> keymap("VSCodes", {
>     # C("Super-Space"):           C("LC-Space"),                  # Basic code completion (conflicts with input switching)
> 
>     # Override the global Cmd+Dot (Escape/cancel) shortcut for QuickFix in VSCode(s)
>     C("RC-Dot"):                C("RC-Dot"),                    # QuickFix, overriding global shortcut
> 
>     C("Super-Grave"):           C("C-j"),                       # Open terminal (Cmd+J also works)
> 
>     # Find dialog options
>     C("Alt-RC-C"):              C("Alt-C"),                     # Find: toggle "Match Case"
>     C("Alt-RC-W"):              C("Alt-W"),                     # Find: toggle "Match Whole Word"
>     C("Alt-RC-R"):              C("Alt-R"),                     # Find: toggle "Use Regular Expression"
>     C("Alt-RC-L"):              C("Alt-L"),                     # Find: toggle "Find in Selection"
>     C("Alt-RC-P"):              C("Alt-P"),                     # Replace: toggle "Preserve Case"
> ```
> 
> This might seem odd, but the physical Ctrl key gets the Super/Meta/Win/Cmd key code when you are in a GUI app like VSCode. This remap seems to work for me, just like the Cmd+J shortcut that I've been using for a long time. I didn't realize there was another shortcut to open the terminal.
> 
> Save the file after you make the edit, then restart Toshy with whichever method you prefer: The tray icon menu item `(Re)Start Toshy Services`, or the button in the GUI preferences app, or the terminal command `toshy-services-restart`. They all do the same thing. Toshy doesn't need to be restarted if you just change preferences from the tray icon menu or Preferences app, but if you make any change to the config file the keymapper has to be restarted to make the change take effect.
> 
> If you can confirm this works for you and does what you want, I'll add this remap to the default Toshy config file so you won't have this issue again if you ever need to reinstall Toshy or install it on another machine (or user account).
> 
> Thanks for the bug report. 👍🏽

Yup that worked! Thank you!

**Comment by RedBearAK** [comment]
> I tried the current version of main and ` + ctl works for toggling the terminal, but ` + shift + ctl is triggering window switching instead of creating a new terminal in vscode.

@mrbrownt 

That would make sense on GNOME, where the default shortcut for in-app window switching seems to be Super+Grave, and the physical Ctrl key becomes Super/Meta/Win. Presumably that would mean Shift+Super+Grave would do the same thing in reverse. 

OK, I checked out the macOS version of VSCode and also took a closer look at what all the related shortcuts are labeled in the default shortcuts file. Looks like I was misunderstanding some things about these shortcuts. 

- Cmd+J is for "Toggle Panel Visibility" (the whole problems/debug/terminal panel)
- Ctrl+Grave is for "Toggle terminal" (show term tab even if you left panel **_not_** showing term)
- Shift+Ctrl+Grave is for "Create New Terminal" (even if the panel isn't showing)

I was a little confused by the last one as it seemed to do something different in another VSCode window, but it was just **_asking for the working directory to use for the new shell_**, which apparently happens if you have more than one folder open at the top level of your workspace. But you probably have seen that before if you've been using this shortcut, and it has nothing to do with Toshy. 

@fervidnerd @mrbrownt 

So these will be my updated proposed remaps to deal with this more correctly: 

```py
keymap("VSCodes", {
    # C("Super-Space"):           C("LC-Space"),                  # Basic code completion (conflicts with input switching)

    # Override the global Cmd+Dot (Escape/cancel) shortcut for QuickFix in VSCode(s)
    C("RC-Dot"):                C("RC-Dot"),                    # QuickFix, overriding global shortcut

    # In-app terminal operations (Cmd+J is "Toggle Panel Visibility" for problems/output/debug/terminal panel)
    C("Super-Grave"):           C("C-Grave"),                   # Terminal: Toggle Terminal
    C("Shift-Super-Grave"):     C("Shift-C-Grave"),             # Terminal: Create New Terminal

    # Find dialog options
    C("Alt-RC-C"):              C("Alt-C"),                     # Find: toggle "Match Case"
    C("Alt-RC-W"):              C("Alt-W"),                     # Find: toggle "Match Whole Word"
    C("Alt-RC-R"):              C("Alt-R"),                     # Find: toggle "Use Regular Expression"
    C("Alt-RC-L"):              C("Alt-L"),                     # Find: toggle "Find in Selection"
    C("Alt-RC-P"):              C("Alt-P"),                     # Replace: toggle "Preserve Case"
```

I put the surrounding lines for context, but these are all you need to update: 

```py
    # In-app terminal operations (Cmd+J is "Toggle Panel Visibility" for problems/output/debug/terminal panel)
    C("Super-Grave"):           C("C-Grave"),                   # Terminal: Toggle Terminal
    C("Shift-Super-Grave"):     C("Shift-C-Grave"),             # Terminal: Create New Terminal
```

If you can both test this update and confirm the behavior of the three shortcuts in the bulleted list above, I can add this to the default Toshy config. 

Make sure you restart Toshy after editing and saving the config file.

**Comment by RedBearAK** [comment]
@mrbrownt @fervidnerd 

Had some other stuff to merge, so I went ahead and merged this into main. If you were to reinstall from a new zip now, you should find these shortcuts working right away without messing with the config file.

**Comment by RedBearAK** [comment]
Closing as completed.
