### ISSUE TITLE
VSCode Terminal Reverse Lookup (Ctrl+r) Not Working

### ISSUE THREAD

**Issue by smetroid** [RedBearAK/toshy#114]
First of all, awesome work, thank you for this tool, definitely makes switching from Mac to Linux and Linux to Mac very easy.

Bare metal or virtual machine: 
`Bare metal`
Linux distro name:  
`Fedora`
Distro version: 
`39`
X11/Xorg or Wayland: 
`Wayland`
Desktop environment(s): 
`KDE`
Any DE(s) tried with Wayland?: 

Keyboard type (IBM, Chromebook, Windows, Apple):
`Windows` 
Keyboard device name (try 'toshy-devices'): 
`Kinesis Freestyle Edge Keyboard System Control`

Problem observed:  

When using the built-in terminal from VSCode, and trying to do a bash reverse lookup (ctrl+r) the command is being ignored, nothing is happening.

When I try the same command in the konsole (Linux-terminal) when no VSCode is involved the reverse lookup works as expected.

Any help is appreciated

**Comment by RedBearAK** [comment]
@smetroid 

Unfortunately the keymapper in Linux (unlike AutoHotkey in Windows) has limited information about the window, and embedded terminals like the one in VSCode don't change either the app class or the window title. So it ends up being impossible to tell that the focus is in the embedded terminal. 

With that said, you should find that the physical equivalent of Cmd+R will bring up the "reverse lookup" thing you're talking about. I literally have never seen this before and don't know what it does. But the point is that the key next to the Space bar becomes a Ctrl key when you are in "GUI" apps and the physical Ctrl key becomes Super/Meta/Win/Cmd. That's why you can't make that shortcut work with physical Ctrl+R while you are in VSCode. Because the keymapper still thinks the embedded terminal is a "GUI" app and not a terminal. In separate terminal apps the physical Ctrl key goes back to being LEFT_CTRL, so this isn't an issue with independent terminal apps. But in both GUI and terminal apps, the key next to the Space bar is actually a Ctrl key. 

If you want to keep using physical Ctrl+R, you can make your own custom keyboard shortcuts either globally in VSCode or per workspace, to override the Super+R shortcut to be Ctrl+R again, when you are in the embedded terminal. With the limitations of the keymapper, I'm afraid there isn't much else that can be done. But VSCode does have a way to set the shortcut only when you are in the embedded terminal, so it wouldn't mess with shortcuts outside of the terminal pane. 

Here are some issue threads on the original Kinto project repo that might be helpful. 

https://github.com/rbreaves/kinto/issues/339  

https://github.com/rbreaves/kinto/issues/605

**Comment by mdrolet01** [comment]
If you don’t have anything mapped to Cmd+R, you can remap it to Ctrl+R for vscode. I did this for Ctrl+D and it kills the terminal as normal (since I don’t use Cmd+D in the editor).

**Comment by RedBearAK** [comment]
A way to deal with this and several other shortcuts in the embedded terminal is now outlined in this Wiki page: 

https://github.com/RedBearAK/toshy/wiki/Embedded-terminal-in-VSCode-and-variants

**Comment by RedBearAK** [comment]
Since this is resolved as well as it can be by the Wiki page linked above, I'm closing this.
