### ISSUE TITLE
How to keep it up to date?

### ISSUE THREAD

**Issue by smileBeda** [RedBearAK/toshy#115]
Hi, very cool and well working tool 

I am wondering what your suggestion is as of how to keep it updated since this is neither an AUR, or else, package.
I am using it on an EndeavourOS T2 install on a mac.
Usually I would just wait until it is worth updating and reinstall the whole thing, but perhaps you have better solutions?

**Comment by RedBearAK** [comment]
@smileBeda 

> how to keep it updated

This is certainly an issue, although I think it's a minor one for practical purposes. I made some effort (as documented in the FAQ) to make it possible to reinstall without damaging some customizations within marked "slices" in the config file. For instance if you need to adjust the macro delay values. So you can indeed check back every few months and just reinstall from the latest zip. But unless there is a particular fix for something you need, it won't really be necessary. 

The installer script also makes a full backup of your preferences database and config file, in case something goes wrong. So you can basically run the installer over and over, and it makes its own Python virtual environment folder with the latest requirements inside. 

I'd like to be able to make Toshy more package-able, but it's been all I could do to make a sort of modular installer script that at least makes it installable on several different Linux distro types, quite a bit more than the original project. Nice to hear that it worked correctly. 

BTW, the GNOME UI for adding new keyboard layouts is truly awful, but if you get to the point where you can search, you should be able to search for "english macintosh" and go inside the "English (United States)" item on the list and find a keyboard layout named "English (Macintosh)". There are actually many different variants of each major layout, but the UI doesn't make this very obvious. They really need to improve that. 

Luckily the Toshy special characters should work well since you're on a US layout. You can change from the standard special characters layout to the "ABC Extended" special characters layout from the tray icon menu. Changing preferences from the tray menu doesn't require restarting Toshy. 

The "ABC Extended" special characters layout has 25 dead keys and far more total characters available. But if all you need are Umlauts you'll do just fine with the standard layout. 

You're also lucky you're on GNOME, where `ibus` is the default. That's what makes the Unicode character sequences actually produce Unicode characters. On KDE Plasma you would have to install `ibus` to have the same effect. 

>  Heck, even clicking enter on a folder, allows to rename that folder just like in macOS (instead of the annooying f2 that gnome wants us to use)

Yes, I had to make a pretty complicated custom function to enable that, and since the keymapper is dealing with limited information it still doesn't always work perfectly. The catch is that when entering text, the Enter key still needs to be Enter. But it works pretty well at this point. I enjoy it. 

Be sure to open other issues if you have any problems or feature requests.

**Comment by smileBeda** [comment]
> For instance if you need to adjust the macro delay values. So you can indeed check back every few months and just reinstall from the latest zip. But unless there is a particular fix for something you need, it won't really be necessary.

Indeed I needed to do that, and the update process is fair enough, thanks!

> BTW, the GNOME UI for adding new keyboard layouts is truly awful, but if you get to the point where you can search, you should be able to search for "english macintosh" and go inside the "English (United States)" item on the list and find a keyboard layout named "English (Macintosh)".

:roll_eyes: - thanks for that hint. Truly very "accessible" lol.

> You're also lucky you're on GNOME, where ibus is the default. That's what makes the Unicode character sequences actually produce Unicode characters. On KDE Plasma you would have to install ibus to have the same effect.

Yeah, I can see the unicode shortly before it transforms into the actual character. For once, gnome is an advantage :D

> Yes, I had to make a pretty complicated custom function to enable that, and since the keymapper is dealing with limited information it still doesn't always work perfectly. The catch is that when entering text, the Enter key still needs to be Enter. But it works pretty well at this point. I enjoy it.

I can only imagine. I tried to create a custom mapping before yet I just could not find the command they use for this... I love the feature, is is _so_ much faster!

Thanks again for all the work and the tool in general, so far it work smooth!
