### ISSUE TITLE
Autostart | Start services on login

### ISSUE THREAD

**Issue by smileBeda** [RedBearAK/toshy#116]
I installed Toshy and everything worked well, but once I logged out and in again I realised the service had to be restarted again in the preferences window (or via terminal)

I read the doc and was a bit confused.
https://github.com/RedBearAK/toshy?tab=readme-ov-file#usage
...
> These are the main commands for managing and checking the services:
> 
> toshy-services-log      (shows journalctl output for Toshy services)
> toshy-services-status   (shows the current state of all Toshy services)
> toshy-services-start
> toshy-services-stop
> toshy-services-restart
> To disable/enable the Toshy services (to prevent or restore autostart at login), use the commands below. It should still be possible to start/restart the services with the commands above if they are disabled. Using the "enable" command in turn will not automatically start the services immediately if they are not running (but the services will then autostart at the next login). > If the services are enabled they can be stopped at any time with the command above, but the enabled services will start automatically at the next login.
> 
> toshy-services-disable  (services can still be started/stopped manually)
> toshy-services-enable   (does not auto-start the service until next login)

If I understand it right I should be able to run `toshy-services-enable` and on the _next login_ the service should autostart.
Yet that was not happening, the service kept being inactive after a logout/login.

I went to the Startup settings of Gnome and saw that toshy had added 2 items:
- one for the tray (which on gnome 45 does not work anymore since they decided trays are something unuseful :shrug: )
- another one that had a lengthly command in it (something with `import` if I recall right)

I decided to remove those and add a custom startup that simply runs `toshy-services-start`
Since then the toshy works just fine upon logout, login, reboot etc.

But I am not sure if I did this right. As it adds the startup items (which I deleted) I guess they are there for a reason and I should add them back?

Can you let me know if they are necessary (I would guess the tray can be omitted), and if the approach above described is somehow inherently wrong?

**Comment by RedBearAK** [comment]
@smileBeda 

I think what you might be running into is a problem that can crop up if you aren't logged out for long enough. Toshy runs a service that attempts to determine whether you are actually actively using a session, and disables the keymapper service if you aren't. The purpose of this is to allow multiple users to use the same system, either with their own keymapper config or with no keymapper config at all. 

With Kinto, it's a system-level service and continues to affect other users if you log out or do a "switch user" sort of operation. I tried to fix that with Toshy by making it run from user service units, but I haven't perfected what happens when you actually log out. It doesn't always restart the keymapper config service when you log back in, particularly if you're not logged out for long enough for the session monitor service to decide to shut down. Still need to work on that aspect. 

But in that case all you should need to do is restart the services from the tray icon menu, or with `toshy-services-restart`, and everything should start working again. There should be no need to mess with the enable/disable commands unless you want the services to be disabled. They aren't disabled, the session monitor service just failed to restart the keymapper service when you logged back in. 

> one for the tray (which on gnome 45 does not work anymore since they decided trays are something unuseful 🤷 )

GNOME removed the built-in support for tray icons a long time ago, but you just need to install the "AppIndicator and KStatusNotifier support" shell extension to get the tray icons back. I think that extension is actually maintained by Ubuntu, so it's almost always available. 

If you don't have the Flathub Flatpak repo set up already, go to https://flathub.org/setup and follow the instructions, then install the "Extension Manager" Flatpak app to have a really easy way to search for, install, enable/disable and manage shell extension settings. 

> another one that had a lengthy command in it (something with import if I recall right)

That one solves a problem I had on various distros with trying to start a user service at login and have it be able to access the full set of environment variables needed to, for instance, automatically determine the desktop environment and whether you're in X11/Xorg or Wayland, so the keymapper config can do the right things. Some different shortcuts need to be enabled for different desktops, and the keymapper has to use a method to get the window info that is specific to the session type and desktop environment as well (in a Wayland session). 

This stuff can also be set manually in the config file, but then it wouldn't adapt automatically if you felt like trying a different desktop environment on the same system, or change your session type. I didn't want users to have to constantly tweak the config file in those cases. Or myself. 

The whole situation around what Toshy has to do to "just work" is much more complicated than it should have been. 

Really the biggest problem was that "switch user" is an option. You can go to the login screen and choose to log in as a different user, while still leaving your original account/desktop logged in. I had to find a way to automatically disable the keymapper in the background session until it became active again, so it wouldn't mess with the foreground user session. It was not easy.

**Comment by RedBearAK** [comment]
@smileBeda 

BTW, if you want to flip the F-keys mode of your MacBook, take a look at the `toshy-fnmode` command. Any keyboard that uses the `hid_apple` driver can be changed to be F-keys first if that's something you find useful. The command has self-explanatory help output, and interactive or non-interactive modes of operation.

**Comment by smileBeda** [comment]
I see, so this might be me not being patient enough.
As I deleted the startup items added by Toshy - do I need to re-install it to bring them back and test again with more patience?
Or are the values available somewhere so I can set them up manually?

---

Indeed usng Gnome tray extension, although from gnome-extensions instead of flatpak, tray works now (I use https://extensions.gnome.org/extension/2890/tray-icons-reloaded/)
Thanks for that, one more thing done.

---

I use macbook with Touchbar and since I am using T2 linux kernel from https://wiki.t2linux.org/ we have inbuilt touchbar support, which actually overwrites the setting of Toshy (I already tried it out)
Also the `tiny-dfr` they use (see https://wiki.t2linux.org/guides/postinstall/#setting-up-the-touch-bar) supports some limited customization of icons and commands, which I still need to get to work, but it is getting closer to macOS native (where I used BTT to make the touchbar actually _useful_)
There's still a long way to go to get to the level of macOS touchbar, but it is a start.

**Comment by RedBearAK** [comment]
> T2 linux kernel

Ah, I wondered what that was about. I fortunately have never encountered a MacBook with the touchbar. 

> gnome-extensions

The GNOME Extensions app is different from the Extension Manager Flatpak app, which has the ability to browse for and install extensions right from the app, instead of installing packages or using a web browser. Minor convenience factor. 

In my experience, if you stay logged out for at least 10-15 seconds before attempting to log in again, things should start automatically again. But let me know if the keymapping doesn't reactivate correctly even after waiting a little while before attempting to log back in. The problem I ran into was that it was strangely not easy to determine from a systemd service process that the user has officially "logged out". The concept of when a session is active seems somewhat nebulous in Linux. There is a `graphical-session.target` that theoretically should have made all this much easier, but in multiple distros that just never worked right. 

> As I deleted the startup items added by Toshy - do I need to re-install it to bring them back and test again with more patience?

Re-running the installer is the simplest way to put all the startup items back where they were. And it goes much faster after the first time, since the native packages will be in place already, and the Python packages are cached. There's a command that would reinstall the two desktop apps, but I don't think it would put back the extra support item or the tray icon in the autostart folder. 

As stated before, the installer tries to keep your customizations in the config file, as long as they were made within the "editable" areas of the file. So reinstalling should not result in loss of functionality or resetting any preferences that you may have tweaked from the GUI app or tray icon menu.

**Comment by RedBearAK** [comment]
Remember to install at least one of the extensions from the Requirements section if you are going to try a Wayland session. Or there will be no app-specific remaps enabled in Wayland. Only the general/GUI remaps will function without a working shell extension that allows the keymapper to acquire the window context info. Terminal apps would behave oddly, the file manager shortcuts like Enter-to-rename would never activate. 

https://github.com/RedBearAK/toshy?tab=readme-ov-file#requirements

**Comment by smileBeda** [comment]
>  I fortunately have never encountered a MacBook with the touchbar.

... for a while it was all you would get if buying new so I bit that apple
.... and then I finally found BTT which _made it actually useful_ 
..... and then Apple said "nah, it's crap we will remove it again".
:shrug: _Same with the magsafe. Best thing ever, removed for years, just to bring it back lol_

> if you are going to try a Wayland session

Wayland has survived exactly 24 hours on my computer, and unless something massive changes in it, I am never going to use it again. _I am all for new, and more secure, etc, but in the end I want to use my computer, not being stopped by the OS or else software because it thinks it can break every useful feature in the name of "modern" or "secure". Same goes for Libadwaita & co_

Thus... I do not need to worry about that :partying_face: 

> In my experience, if you stay logged out for at least 10-15 seconds before attempting to log in again, things should start automatically again

I reinstalled, logged out and waited for a bit more time and it works just fine.
No further anything was needed.
häppïly using my ümlāüte and keyboard combos :D :D

**Comment by RedBearAK** [comment]
@smileBeda 

> I reinstalled, logged out and waited for a bit more time and it works just fine.

Good to hear, but I think I will reopen this issue and leave it as a reminder to look at the short-logout problem again. It should be possible to refine it a bit more. Thanks for the issue report. 

>  häppïly using my ümlāüte and keyboard combos :D :D

Møst éxcèllëñt. 👍🏽

**Comment by RedBearAK** [comment]
I forgot that the main aspect of this issue is actually not my fault precisely, and has little to do with my attempt at "switch user" multi-user support. What's happening when you actually completely log out of your session is that `systemd` is failing to quickly terminate the "user" services even though the user session is gone. This is really kind of a bug with how `systemd` deals with "user" services that are tied to the user's login session. User-based service units should just instantly be terminated as soon as you log out, but it actually seems to take `systemd` several seconds to recognize that your session is over, and return to a "clean slate" state for that user. 

The solution, most likely, will involve a forced restart of the services upon login, to overcome the problem of the "sleeping" session monitor service under these short logout-login circumstances. In theory the stuff started at login will always be started again, even if the user has only logged out for a very brief moment before logging back in. The act of logging in is far less nebulous in Linux than the act of logging out. 

This  is a reminder to me, to try implementing this when I get some time.

**Comment by RedBearAK** [comment]
@smileBeda 

I have some changes in the `login_kickstart` branch of the project that should fix the "short logout" problem. Basically it restarts the services if the session monitor service is enabled but not active a few seconds after logging in. It may seem to take a couple of extra seconds, but it is working for me. 

I tried to make sure it wouldn't have bad side effects like starting the services when they are supposed to be disabled. That shouldn't happen. But Toshy should re-activate by itself on those occasions when the user doesn't count to 10 before logging back in. 

If you get a change to do a re-install from that `login_kickstart` branch and can test the logging out and quickly logging back in, let me know. 

Happy New Year!

**Comment by RedBearAK** [comment]
I merged the autostart changes into the main branch, so I'll probably be deleting the `login_kickstart` branch now. You should get better behavior after a quick logout-login now, even if you re-install from a zip of the main branch. 

Put an "@" mention for me on this issue or open a new one if you see any further problems.
