### ISSUE TITLE
[BUG] Held-down keys repeat, even with rate set to 1 

### ISSUE THREAD

**Issue by Daria-E** [RedBearAK/toshy#137]
```
Bare metal or virtual machine: Bare metal

(Try running 'toshy-env' in a terminal.)

DISTRO_NAME     = 'debian'
DISTRO_VER      = '12'
VARIANT_ID      = 'notfound'
SESSION_TYPE    = 'wayland'
DESKTOP_ENV     = 'kde'
DE_MAJ_VER      = '5'


Keyboard type (IBM, Chromebook, Windows, Apple): Auto-adapt
Keyboard device name (try 'toshy-devices'): AT Translated Set 2 keyboard (Framework laptop)
```

Problem observed:  
When holding down keys, the keep repeating. As per the README, I tried changing the repeat rate in Plasma Settings -> Keyboard - but even when changing c/s to 1 they still repeat. Changing keyboard type to Windows doesn't solve this issue.

**Comment by RedBearAK** [comment]
@Daria-E 

I need a lot more context around this, to understand exactly what is happening and why it is a problem for you. 

For instance, are you expecting "normal" keys to never repeat, like in macOS? Because the keymapper would have to be modified in order to mimic that. I kind of played around with that at one point, but I'm not the original developer of the keymapper. 

Or, are you talking more about repeating modifier keys, which normally send out a "repeat" signal if they are held down? 

Is the problem that the keys still repeat faster than the rate of 1 cps, as if the setting of the repeat rate didn't work? Does the slow repeat rate behave like it should when Toshy is disabled? 

Why is the repeating considered a problem in your use case? Where exactly does the repeating happen? In a specific location or in all apps? 

The keymapper creates a virtual keyboard, and the repeat rate of the virtual device might need to be changed in order to really slow down the repeating to match what you're trying to achieve.

**Comment by RedBearAK** [comment]
@Daria-E 

In a Wayland session on Fedora 39 (GNOME) I'm finding that the minimum repeat rate I can set with the `kbdrate` utility in the terminal is 2.0 cps and the maximum delay time is 1000 ms. Using the GNOME Accessibility -> Typing settings sliders for repeat rate, the delay can be increased, but the minimum repeat rate seems about the same speed. 

As noted it is normal for regular (non-modifier) keys to repeat in Linux, unlike macOS, and modifier keys as far as I know need to repeat so that apps know they are still being held down. So without more detail I can't really know what the "problem" is or what would fix it.

**Comment by RedBearAK** [comment]
@Daria-E 

I'm seeing a way to completely disable repeating on both GNOME and KDE Plasma settings. I feel like I may have run into some problems when I completely disabled repeating, but maybe I'm thinking about what happened when I attempted to modify the keymapper to disable repeating internally. The repeat rate can be much slower on KDE, and the delay much longer (5 seconds). But there are also a pair of radio buttons above the sliders where you can choose "Do nothing" in order to disable repeating keys. 

There is information on terminal commands related to repeat rate in this Wiki entry: 

https://github.com/RedBearAK/toshy/wiki/Repeating-Keys-Settings

**Comment by Daria-E** [comment]
Thanks very much for your attention, and apologies for not being more specific.

My issue was that keys were repeating after I stopped holding down the button (as described [here](https://github.com/RedBearAK/toshy#repeating-keys). Changing repeat rate settings didn't fix the problem, but it seems a reboot did...

If it ever comes up again I'll comment here with more details, but for now I think this issue can be closed.
