### ISSUE TITLE
Changing input souce (language) with cmd+space instead of ctrl+space

### ISSUE THREAD

**Issue by c0untd0wn** [RedBearAK/toshy#144]
While I was searching for a way to make Kinto.sh work on Wayland, I managed to find this project, which works like a charm!

There is one feature that I would like to have for Toshy.

In the old days, the command for input source change used to be cmd+space on macOS, which has been changed to ctrl+space as the default since Sierra.
Since I've been working with macs for more than a decade, I still use cmd+space for input source change in my Macbook Air.

It would be useful if there is a way to change the command for input source change.
Thank you in advance for your support!

**Comment by RedBearAK** [comment]
@c0untd0wn 

> In the old days, the command for input source change used to be cmd+space on macOS, which has been changed to ctrl+space as the default since Sierra.

I think you might be right about that. Things have changed a lot since Cheetah/Jaguar, eh? 😆 

I certainly won't be changing the defaults, but you can do an override, and if you do it right it should survive a re-install of Toshy. So you could come back a few times a year and get new updates to your config by downloading a new zip to install from. 

If you take a look at the config file (toshy_config.py) in the folder that you should be able to open from the tray icon menu, it has marked "slices" where any edits will be copied and re-applied to the new copy of the config file during a re-install. 

It would be irresponsible of me to not mention that you may run into some pretty odd behavior of certain shortcuts while using another keyboard layout, because the keymapper doesn't have any understanding of layouts other than the standard US layout. 

Another way to look at this defect is that keyboard shortcuts will do the same thing from the same keys **_regardless of which layout you switch to_**. Depending on your point of view, this could be a better situation than what might normally happen on macOS. 🤷🏽‍♂️ 

Anyway, to do the override, open the config folder and open the `toshy_config.py` file for editing. Put something like this in the "User Apps" section that looks like this: 

```py
####################################  USER APPS  #####################################
###                                                                                ###
###                                                                                ###
###      ██    ██ ███████ ███████ ██████       █████  ██████  ██████  ███████      ###
###      ██    ██ ██      ██      ██   ██     ██   ██ ██   ██ ██   ██ ██           ###
###      ██    ██ ███████ █████   ██████      ███████ ██████  ██████  ███████      ###
###      ██    ██      ██ ██      ██   ██     ██   ██ ██      ██           ██      ###
###       ██████  ███████ ███████ ██   ██     ██   ██ ██      ██      ███████      ###
###                                                                                ###
###                                                                                ###
######################################################################################
### This is a good location in the config file for adding new custom keymaps for 
### user applications and custom function keys. Watch out that you don't override 
### any "general" shortcuts like Cmd+Z/X/C/V that may be defined below this section. 
### Changes made between the "slice" marks will be retained by the Toshy installer 
### if you reinstall and it finds matching start/end markers for each section. 

###################################################################################################
###  SLICE_MARK_START: user_apps  ###  EDITS OUTSIDE THESE MARKS WILL BE LOST ON UPGRADE


keymap("User overrides terminals", {
    C("LC-Space"):              [iEF2NT(),C("THE-REAL-COMBO-FOR-SOME-LAUNCHER")],    # Spotlight equivalent
    C("Shift-LC-Space"):        None,    # block the default general terminals shortcut for input switching
}, when = matchProps(lst=terminals_lod))

keymap("User overrides general", {
    C("Super-Space"):           [iEF2NT(),C("THE-REAL-COMBO-FOR-SOME-LAUNCHER")],    # Spotlight equivalent
    ### Keyboard input source (language/layout) switching
    C("RC-Space"):              [bind,C("THE-REAL-COMBO-FOR-INPUT-SWITCHING")],    # input switch forward
    C("Shift-RC-Space"):        [bind,C("THE-REAL-COMBO-FOR-REVERSE-INPUT-SWITCHING")],    # input switch reverse (OPTIONAL)
}, when = matchProps(not_lst=remotes_lod))

###  SLICE_MARK_END: user_apps  ###  EDITS OUTSIDE THESE MARKS WILL BE LOST ON UPGRADE
###################################################################################################

```

The combos in "ALL-CAPS" on each line will need to be replaced by the correct combos for your desktop environment and chosen launcher/Spotlight equivalent. I can't predict what those would be in your specific case. Just put the shortcut combo you would use for those functions if Toshy was disabled. 

You will need to save the file and then restart Toshy (services) from the tray icon menu or with `toshy-services-restart` in the terminal. Preferences from the tray icon menu will apply immediately, but the keymapper process must be restarted anytime the config file changes. 

Let me know if you have any trouble getting this to work. 

The one marked "User overrides general" here is also a good place to put fixes for hardware/media key remaps specific to your machine.

**Comment by c0untd0wn** [comment]
Thank you for the prompt response! This is exactly what I was looking for.

Now, I have cmd+space assigned to input source change and ctrl+space assigned to the GNOME shell 'Search Light' extension, respectively.

I appreciate your efforts that made this possible on Wayland! :+1:
