### ISSUE TITLE
(Enh) Mode to allow raw NumPad keys to pass through. 

### ISSUE THREAD

**Issue by leejoramo-d51** [RedBearAK/toshy#169]
**Is your feature request related to a problem? Please describe.**

I would like a mode to allow the keyboards native Numpad codes to pass through.

My use case is that I have a mechanical keyboard with layers. One of the layers I have assigned the Numpad keys to keys on the left side of my keyboard: 
```
q:KP7 w:KP8 e:KP9
a:KP4 s:KP5 d:KP6
z:KP1 x:KP2 c:KP3
```
Because the Numeric Keypad keys can be distinguished from the normal number and curor keys, I assign them in **KDE's Shortcuts->KWin** to move the current window to a position on the screen: 

![image](https://github.com/RedBearAK/toshy/assets/36970352/5b2d061d-f118-4893-9f27-8f09213d4369)

So now on my mechanical keyboards layer hitting `q` moves the window to the Top Left, `w` to the Top Half and so on. 

**Describe the solution you'd like**
It would be nice to add a toggle switch for this in the GUI, but I am fine with it being done only in my own custom code or configuration.

*If it is done in custom code, what is the best practice to maintain this with upgrades to toshy?*

**Describe alternatives you've considered**

Here is how I modified `toshy_config.py`. First I set a variable: `use_native_numpad = True`

Then I modified two modmaps:

```py
modmap("Cond modmap - Forced Numpad feature",{
    # Make numpad be a numpad regardless of Numlock state (like an Apple keyboard in macOS)
    Key.KP1:                    Key.KEY_1,
    ...
}, when = lambda ctx:
    matchProps(not_lst=exclude_kpad_devs_lod)(ctx) and
    matchProps(not_lst=remotes_lod)(ctx) and
    cnfg.forced_numpad is True and
    use_native_numpad is False)   # add conditional to pass numpad keys  
```
I added a similar section to the `modmap("Cond modmap - GTK3 numpad nav keys fix"` 

**Additional context**
I just tried `toshy` today for the first time after using `kinto` for years. So far it has fixed a few rough edges and I think toshy's code looks much more approachable and polished. This was the only issue I have run into compared to kinto. 

Thanks!

**Comment by RedBearAK** [comment]
@leejoramo-d51 

> If it is done in custom code, what is the best practice to maintain this with upgrades to toshy?

I can pretty easily add another customizable "slice" that would survive a Toshy re-install, just like the other existing marked slices. But first I need to read this over several more times and see if I can understand the actual issue. My initial impression is that perhaps it would be more sensible to just disable the Forced Numpad feature from the Preferences menu (tray icon) or the separate Preferences app. 

I was actually starting to consider completely removing the GTK3 fix modmap, since so many common apps are GTK4 already and almost nobody probably ever needed that fix in the first place. 

Once that modmap is disabled/gone and you turn Forced Numpad off, won't that do what you're looking for, by letting the `KP*` keys through without being modmapped into "normal" numeric key names? 

With the keypad keys on a layer the Forced Numpad modmap is not really serving any purpose in your case anyway. It's meant to allow typing numbers on a PC-style keyboard with keypad, without needing to think about the NumLock state. So it kind of acts more like an Apple keyboard keypad. 

Interested to hear back on this. 

> I just tried toshy today for the first time after using kinto for years. So far it has fixed a few rough edges and I think toshy's code looks much more approachable and polished. This was the only issue I have run into compared to kinto.

I appreciate when anybody besides me can get some real use out of this project, and I've done my best to make its structure logical and flexible wherever possible. Never really meant to replace Kinto, but the dev didn't have the time to keep up with the continuous modifications I was making. 

Do let me know about any and all problems you encounter.

**Comment by RedBearAK** [comment]
@leejoramo-d51 

And then of course there is this, which I basically forgot all about. 

```py
###################################################################################################
###  SLICE_MARK_START: exclude_kpad_devs  ###  EDITS OUTSIDE THESE MARKS WILL BE LOST ON UPGRADE

# List of devices to add to the device exclusion list below this slice
# How to use this list to exclude additional keypad devices:
# Put device names in individual Python "{dictionaries}".
# Make the dictionaries look exactly like the given example, 
# including the comma after each dictionary.

exclude_kpad_devs_UserCustom_lod = [
    # {devn:'My Keyboard Device'},
    #
]

###  SLICE_MARK_END: exclude_kpad_devs  ###  EDITS OUTSIDE THESE MARKS WILL BE LOST ON UPGRADE
###################################################################################################
```

This was added to the config because of some mouse with keypad keys on it, where someone wanted to use the raw keypad keys for shortcuts. If you just add your keyboard device name to the custom dict, the device will be excluded from both of the keypad-related modmaps. 

The device name will appear in the diagnostic dialog: 

`Shift+Opt+Cmd+I,I` (quickly double-tap the "I" key while holding the mods)

A Zenity dialog should appear showing the relevant context. Application class, window title and keyboard device name.

**Comment by RedBearAK** [comment]
@leejoramo-d51 

Be aware that some keyboard devices will appear with different names depending on how you connect to the computer. If sometimes you use USB and other times it is a Bluetooth device, check that the device name remains the same. If it uses a different name on Bluetooth or a wireless USB dongle, each name will need to be added to the exclusion list.

**Comment by leejoramo-d51** [comment]
Adding `Kinesis Freestyle Edge Keyboard` to `exclude_kpad_devs_UserCustom_lod` does the trick for me. Since that is currently will survive most any updates, I will go this way. Thank You

> With the keypad keys on a layer the Forced Numpad modmap is not really serving any purpose in your case anyway. It's meant to allow typing numbers on a PC-style keyboard with keypad, without needing to think about the NumLock state. So it kind of acts more like an Apple keyboard keypad.

Not sure if this was clear, but the reason for using the Numpad keys is that they are **never** used for their original purpose in my use case. I have an  [Kinesis Freestyle Edge](https://gaming.kinesis-ergo.com/edge/) which has no Numpad, so I can safely remap KDE to use these keys for moving the windows. 

Lots of layers here, hardware keyboard macros, toshy, KDE Shortcut remaps, but it bends the system to my my style.

**Comment by RedBearAK** [comment]
> Not sure if this was clear, but the reason for using the Numpad keys is that they are never used for their original purpose in my use case. I have an [Kinesis Freestyle Edge](https://gaming.kinesis-ergo.com/edge/) which has no Numpad, so I can safely remap KDE to use these keys for moving the windows.

I understand the concept. What I meant was just that you would already not get to enjoy the "convenience factor" of a separate physical keypad pretending to be "real" number keys as a hack to make the keypad work like an Apple keyboard. You always have to hold something that lets you get to those assigned keypad keys, so the modmaps that transform keypad keys were just getting in the way rather than doing anything beneficial. 

Fortunately due to the previous user with a funny mouse with keypad keys, the exclusion list gets the job done, bypassing both of those modmaps when using that device. But you could still plug in an entire separate keyboard with keypad, or just a dedicated keypad device, and those modmaps would apply to that device unless it was also added to the exclusion list. 

Since this solution accomplishes what you were requesting, I'll consider this resolved. 

Thanks for the detailed issue. Feel free to submit an issue for anything else that seems to get in the way or doesn't work quite right. We will often be able to figure something out, even if it doesn't get included in the default config.
