### ISSUE TITLE
[BUG] Detects Mouse as Keyboard, so mappings are messed up as described in #20

### ISSUE THREAD

**Issue by git-jonathankinney** [RedBearAK/toshy#178]
```
Bare metal or virtual machine: Bare metal

		 DISTRO_NAME     = 'ubuntu'
		 DISTRO_VER      = '22.04'
		 VARIANT_ID      = 'notfound'
		 SESSION_TYPE    = 'x11'
		 DESKTOP_ENV     = 'gnome'
		 DE_MAJ_VER      = '42'


Any DE(s) tried with Wayland?:  No

Keyboard type:  US full sized Dell multimedia USB, via hub.
Keyboard device name (try 'toshy-devices'): 

/dev/input/event3    DELL Dell USB Wired Multimedia Keyboard
/dev/input/event4    DELL Dell USB Wired Multimedia Keyboard System Control
/dev/input/event5    DELL Dell USB Wired Multimedia Keyboard Consumer Control
/dev/input/event8    USB OPTICAL MOUSE  Keyboard         usb-0000:07:00.0-2.4.1/input1

```

These terminal commands may provide helpful info:

- toshy-services-log  
```
Feb 24 14:47:06 Black-Beast systemd[1793]: Stopping Toshy Config Service...
Feb 24 14:47:06 Black-Beast bash[10826]: keyszer v0.7.1
Feb 24 14:47:06 Black-Beast bash[10826]: (--) WATCH: Watching for new devices to hot-plug.
Feb 24 14:47:06 Black-Beast bash[10826]: (--) Autodetecting all keyboards (--device not specified)
Feb 24 14:47:06 Black-Beast bash[10826]: (+K) Grabbing 'DELL Dell USB Wired Multimedia Keyboard' (/dev/input/event3)
Feb 24 14:47:06 Black-Beast bash[10826]: (+K) Grabbing 'USB OPTICAL MOUSE  Keyboard' (/dev/input/event8)
Feb 24 14:47:06 Black-Beast bash[10826]: (--) Ready to process input.
Feb 24 14:47:06 Black-Beast bash[10826]: signal TERM received
Feb 24 14:47:06 Black-Beast bash[10826]: (-K) Ungrabbing: 'DELL Dell USB Wired Multimedia Keyboard' (removed)
Feb 24 14:47:06 Black-Beast systemd[1793]: Stopped Toshy Config Service.
Feb 24 14:47:06 Black-Beast systemd[1793]: toshy-config.service: Consumed 2.301s CPU time.
Feb 24 17:21:35 Black-Beast systemd[1793]: Starting Toshy KDE D-Bus Service...
Feb 24 17:21:35 Black-Beast systemd[1793]: Started Toshy KDE D-Bus Service.
Feb 24 17:21:36 Black-Beast systemd[1793]: Starting Toshy Config Service...
Feb 24 17:21:36 Black-Beast systemd[1793]: Started Toshy Config Service.
Feb 24 17:21:36 Black-Beast systemd[1793]: Started Toshy Session Monitor.
```
- toshy-services-status  
```Services are fine, skipping```
- toshy-config-start-verbose  
```
non-network local connections being added to access control list
keyszer v0.7.1
(DD) CONFIG: /home/bart/.config/toshy/toshy_config.py
(DD) THROTTLES: Pre-key: 12ms, Post-key: 18ms
(DD) No Synergy log folder found. No log observer will be engaged.

(CG) Current settings:
        -------------------------------------------
        calling_module      = 'toshy_config.py'
        db_file_path        = '/home/bart/.config/toshy/toshy_user_preferences.sqlite'
        -------------------------------------------
        gui_dark_theme      = True
        -------------------------------------------
        override_kbtype     = 'Auto-Adapt'
        -------------------------------------------
        optspec_layout      = 'US'
        -------------------------------------------
        forced_numpad       = True
        media_arrows_fix    = False
        multi_lang          = False
        Caps2Cmd            = False
        Caps2Esc_Cmd        = False
        Enter2Ent_Cmd       = False
        ST3_in_VSCode       = False
        -------------------------------------------

(CG) Toshy config sees this environment:
	DISTRO_NAME      = 'ubuntu'
	DISTRO_VER       = '22.04'
	SESSION_TYPE     = 'x11'
	DESKTOP_ENV      = 'gnome'
	DE_MAJ_VER       = '42'

(DD) ENVIRON: Session type: 'x11', Desktop env: 'None'
(DD) Zenity command path: '/usr/bin/zenity'
(--) WATCH: Watching for new devices to hot-plug.
(--) Autodetecting all keyboards (--device not specified)
(+K) Grabbing 'DELL Dell USB Wired Multimedia Keyboard' (/dev/input/event3)
(+K) Grabbing 'USB OPTICAL MOUSE  Keyboard' (/dev/input/event8)
(--) Ready to process input.
```
- toshy-devices
```Already listed above```
- toshy-env
```Already listed above```

Problem observed:  
* * *
Very similar copy and paste issues as https://github.com/RedBearAK/toshy/issues/20, with the strange character vomit when copying and pasting the way I would normally using this same keyboard and mouse for my apple computers.  The super/logo key (windows logo key on this keyboard), + the c/v is what I first tried.  Luckily I can just use alt-c and alt-v for some reason, for copy and paste.  I suspect its the 'USB OPTICAL MOUSE  Keyboard' being "Grabbed".  I never really knew why it detected the 2 devices for one mouse, but it could be some additional functionality, or built in malware installer feature that comes with cheap mice?  Is there a quick way to exclude a device from being detected as a keyboard?  I forced a windows keyboard detection, no change.  I added a definition for the actual keyboard to the config, no change.  I will dig a bit more into keyszer docs to see if there is a config or quick way to exclude a device.  Nothing about this install should be special, just the default Ubuntu desktop that is installed from this version of Ubuntu.

**Comment by RedBearAK** [comment]
@git-jonathankinney 

Thanks for having a fairly thorough report. However I'm a bit confused about what the actual problem is. 

> The super/logo key (windows logo key on this keyboard), + the c/v is what I first tried. Luckily I can just use alt-c and alt-v for some reason, for copy and paste.

If this is a Windows style keyboard, with `Alt` on either side of the Space bar, the usual cut/copy/paste shortcuts should be the keys that are in the same physical locations as Cmd+X/C/V on an Apple keyboard. 

The keymapper config first moves modifier key positions around, based on which keyboard type you're using, to retain the muscle memory from using an Apple keyboard on macOS. 

It sounds like you've been using this Dell keyboard with macOS without asking macOS to swap the modifier keys so that it would behave more like an Apple keyboard. Which is something you can do from the keyboard preferences in macOS, to more easily use Windows-style keyboards with macOS without messing with muscle memory. 

>  I forced a windows keyboard detection, no change.

This part goes along with my understanding of the situation, which is that the Dell should be getting automatically treated as a "Windows" type keyboard, which means that forcing Toshy to identify it as a "Windows" type wouldn't change anything. It might actually make more sense in this situation, if you really don't want to type on the keyboard as if it is an Apple keyboard (using the `Alt` key as if it was a `Cmd` key), to try forcing the "Apple" type, or identify the specific Dell keyboard device in the config file as "Apple" rather than a "Windows" type keyboard. 

But the whole point of the way the config is set up is to allow going back and forth between a real Apple keyboard on macOS and a PC or IBM keyboard on a Mac or PC running Linux, and not really be able to tell the physical difference in which keys you're using. 

I believe the detection of the USB mouse is unrelated to your problem, and may be happening merely because for some reason the mouse device name includes "keyboard". But having the mouse device detected should also keep you from having to edit the `suspend` timeout to keep from having issues with the `Alt` key in Firefox or VSCode variants, or other apps that focus the menu bar when you press `Alt`. 

Let me know if anything about this explanation doesn't make sense. 

You can disable the Option key special characters from the tray icon menu, but as long as you don't try to use the Meta/Super/Win key as the Command key, you should never see them. Use the `Alt` key as the `Cmd` key replacement, and the Super/Meta/Win key is meant to be the replacement for Option/Alt. It's all about the physical position of the keys, not their labels. 

Try to just use the keyboard as if it was a real Apple keyboard.

**Comment by git-jonathankinney** [comment]
LOL, perfect response, I had no idea.  I have been using a MacOS MBP for over 12 years now, with basically a windows keyboard without changing any MacOS settings to interpret the keyboard as anything other than what it chose after the simple keyboard identification process.  I had no idea that somehow using alt was a normal thing in relation to an actual Apple keyboard, which I have never actually used before, other than what is on the MBP.  So, if when using a Windows keyboard as a Apple keyboard, this is all "normal", then I am super happy to continue the lies I have been living, and tell toshy that I am using an Apple keyboard, just like MacOS would choose by default.  I have gotten so used to what ever it chose as the right way to interpret my keyboard, that I had no idea I was "doing it wrong" by any perspective.  With that simple change (telling toshy that I am using an Apple keyboard) everything works wonderfully, thanks for connecting the dots for me.

**Comment by git-jonathankinney** [comment]
I can't fathom I am the only one to run into this.  Maybe to catch others that just obey what Apple says you should do with a windows keyboard, it might be a good opportunity to include some documentation to prevent similar "bug" reports of what is normal and expected behavior.  I could not care less if I have to tell it to treat my Dell Windows keyboard as if it were an Apple keyboard.  The end result of full continuity is a joy, and a boost to productivity.

**Comment by RedBearAK** [comment]
@git-jonathankinney 

> I can't fathom I am the only one to run into this.

I do have another open issue from someone who was assuming that the Meta/Super/Win key was supposed to be the Command key equivalent, but I think once that person grasps the way the modifiers are shifted around by the keymapper I think they will be fine treating their keyboard as if it was an Apple keyboard. 

Yours is an unusual case of getting used to the Cmd/Option modifiers technically being in the "wrong" place compared to any real Apple keyboard. I'm just glad the Apple-type modifier remap will allow you to keep using the device the way you prefer. 

Be aware that if you get a new (Windows-type) keyboard you'll have to do the same thing, forcing the Toshy config to treat it as an Apple type keyboard. This will never happen naturally with keyboards that don't identify as something like "Apple Keyboard" or "Magic Keyboard". Basically you'll always be going against the algorithm that identifies the keyboard type, which defaults to "Windows" type for anything that it can't identify as being something else. 

Same should be true if you ever try to use a real Apple keyboard, you'd probably need to force Toshy to treat it as a "Windows" keyboard type, to make the modifiers appear to be in the position that you got used to. No big deal, just something to be aware of if you ever change keyboards. 

Actually that would apply also to the internal keyboard of the MacBook Pro. So you could make the built-in keyboard of the MBP behave the same way as the external keyboard, by using the custom keyboard type option in the config. Sounds like you almost never use it, but if you needed to, that would be a way to enforce consistency between them. 

If you used the "forced" option from the tray menu, the config won't adapt per-device in the same way, in real-time. I highly recommend fixing this in the config file, for each device. 

>  The end result of full continuity is a joy, and a boost to productivity.

Yep. Have fun.
