### ISSUE TITLE
[BUG] ~2 second delay registering Command + mouse hover

### ISSUE THREAD

**Issue by thtas** [RedBearAK/toshy#18]
```
Bare metal or virtual machine: Bare metal

(EV) Toshy env module sees this environment:
		 DISTRO_NAME     = 'ubuntu'
		 DISTRO_VER      = '23.04'
		 SESSION_TYPE    = 'wayland'
		 DESKTOP_ENV     = 'gnome'


DE(s) tried with Wayland?: Yes both X11 and Wayland
```
Problem observed:  
* * *
Really just a niggle: 

I'm using this machine primarily for coding, and noticed when trying to inspect functions in my IDE I could normally (under ubuntu22+kinto) hold command and hover the mouse over a class or function which would show a function signature or other contextual information. This info would show instantly. But oddly now under Toshy, there seems to be a bit of a delay where the app (php storm) isn't recognizing the command + hover state for a good few seconds.

Could this be something to do with Toshy? Is it doing something to register a command key hold that could be confusing this app that is looking for a hold + hover? Something i can configure?

(P.S. I'm really loving your work here and fantastic to have it working in Wayland , thank you!).

**Comment by RedBearAK** [comment]
@thtas 

Glad you're enjoying it, mostly! 👍🏽  Yeah, I was really driven to get it working in some Wayland environments (although it is still limited to GNOME and/or KDE) so that more people could enjoy Mac-like shortcuts without being forced to continue using only X11/Xorg. 

Here's what you've probably got going on: 

Kinto still uses `xkeysnail` as the actual keymapper, which had a number of issues of its own and was forked and renamed `kesyzer`, which Toshy uses. One of the features of `keyszer` was an attempt at "hiding" mod key presses from applications to try and prevent the improper activation of menus and such in apps like Firefox or VSCode. (There is a FAQ entry about fixing this for those apps.)

So basically there is a "suspend" timeout in `keyszer` that defaults to 1 second (which if you count fast might feel like 2 seconds). This works pretty well with regular mouse devices, not so well with touchpads. I think in your case where it is supposed to enable some hover information there is no "event" like a mouse click to pair up with the mod key press and let it through the suspend timer immediately so that the app can see it. That's how things work when you actually click or do a key combo with the suspended mod key. 

On my laptop I've always had to disable or drastically reduce the suspend timeout length from the default of 1 second to 0.1 second, so that I can `Cmd+click` links in new tabs and `Shift+click` to select things while using a touchpad on a laptop. 

This is all documented in a FAQ entry that should show you how to overcome the issue. 

https://github.com/RedBearAK/toshy#touchpadstrackpads-and-keyszer-suspend-timer

I would encourage you to download a new zip from the `dev_beta` branch of the repo and do a reinstall before you start editing anything in the `toshy_config.py` file. I've implemented a number of features that should help retain user customizations of the config and saved preferences going forward. I will probably merge it all into `main` shortly, but I haven't yet. 

You can open the config folder easily from the tray icon menu, in case you haven't noticed that yet. 

Please let me know how it goes. 🤨 🤔

**Comment by thtas** [comment]
Aha, i see you've just merged it in to main. I will try it out when i can get it working again >.<  - See #20

**Comment by RedBearAK** [comment]
Added the suggested fix for the Magic Keyboard to the default config as well. Hopefully that will no longer be a problem for anyone with that type of keyboard.

**Comment by thtas** [comment]
I tried setting `suspend` to 0.1 and this has made things much better. thanks!

**Comment by RedBearAK** [comment]
> I tried setting `suspend` to 0.1 and this has made things much better. thanks!

I figured that would do it. You can close this issue if you think the problem is taken care of. If you close it yourself you'll be able to re-open it if you need to. Or I'll close it after some time.

**Comment by thtas** [comment]
closing then :)

**Comment by thtas** [comment]
0.5 seconds was the sweet spot in the end.
