### ISSUE TITLE
is this support in phpstorm or webstorm?

### ISSUE THREAD

**Issue by MNhat0308** [RedBearAK/toshy#191]

**Comment by RedBearAK** [comment]
@MNhat0308 

It has a JetBrains keymap, and all general shortcuts should work. 

```py
}, when = matchProps(clas="^jetbrains-(?!.*toolbox).*$"))
```

You’d have to try it and see if anything doesn’t work as expected.

**Comment by MNhat0308** [comment]
> @MNhat0308
> 
> It has a JetBrains keymap, and all general shortcuts should work.
> 
> ```python
> }, when = matchProps(clas="^jetbrains-(?!.*toolbox).*$"))
> ```
> 
> You’d have to try it and see if anything doesn’t work as expected.

where is that code come from? i cannot see that

**Comment by RedBearAK** [comment]
https://github.com/RedBearAK/toshy/blob/714a9565f4ba9f52efb07f197fdc4cf8c0461385/default-toshy-config/toshy_config.py#L3319

**Comment by MNhat0308** [comment]
> https://github.com/RedBearAK/toshy/blob/714a9565f4ba9f52efb07f197fdc4cf8c0461385/default-toshy-config/toshy_config.py#L3319

in webstorm have option chose keymap
in this toshy ,what is option we can choose?

**Comment by MNhat0308** [comment]
> > @MNhat0308
> > It has a JetBrains keymap, and all general shortcuts should work.
> > ```python
> > }, when = matchProps(clas="^jetbrains-(?!.*toolbox).*$"))
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > You’d have to try it and see if anything doesn’t work as expected.
> 
> where is that code come from? i cannot see that

and one more things, i install jet brains through snap
not install by toolbox

**Comment by RedBearAK** [comment]
Were you able to see the app class with the diagnostic dialog shortcut? Maybe it’s not matching on the existing keymap conditional. But we would need to know the app class, if it is different.

**Comment by MNhat0308** [comment]
> Were you able to see the app class with the diagnostic dialog shortcut? Maybe it’s not matching on the existing keymap conditional. But we would need to know the app class, if it is different.

i will try and response here soon

**Comment by MNhat0308** [comment]
it show "jetbrains-webstorm"
so next step go to toshy_config.py
and copy another jet brains like this right
![image](https://github.com/RedBearAK/toshy/assets/57012342/933672b4-62d4-4321-97a4-715c443dd6fe)

**Comment by RedBearAK** [comment]
You can combine multiple app class strings together into the same pattern, fortunately. No need to copy the whole keymap unless there are keyboard shortcuts specific to WebStorm. That seems unlikely. 

```py
}, when = matchProps(clas="^jetbrains-(?!.*toolbox).*$|^jetbrains-webstorm$|^jetbrains-phpstorm$"))
```

That should match on all the relevant patterns for now, and the keymap will activate for you with the Snap apps. You have to restart Toshy any time you change the config file like this, so the new code will be active. 

But if this is a general pattern with the Snap versions of the JetBrains apps, I'll probably start adding a JetBrains list to the default Toshy config file so this isn't a problem for anyone else. Would you be able to verify the app class of PHPStorm or other JetBrains apps when they are installed via Snap?

**Comment by RedBearAK** [comment]
@MNhat0308 

Would you mind reinstalling Toshy to test a change in the default config file? I've changed that keymap to using a list of app classes, to make it easier to add new ones later, if necessary. 

```py
# new app classes show up on JetBrains apps installed via Snap
jetbrains_lod = [
    {clas:"^jetbrains-(?!.*toolbox).*$"                         },
    {clas:"^jetbrains-webstorm$"                                },
    {clas:"^jetbrains-phpstorm$"                                },
]

…

# }, when = matchProps(clas="^jetbrains-(?!.*toolbox).*$"))
}, when = matchProps(lst=jetbrains_lod) )
```

Reinstalling should be safe as long as any customizations of the config file that should be retained are inside the "slice marks" comment lines. 

Get the new zip file from here, it's a new branch for testing this change: 

https://github.com/RedBearAK/toshy/tree/jetbrains_list_test

**Comment by MNhat0308** [comment]
> @MNhat0308
> 
> Would you mind reinstalling Toshy to test a change in the default config file? I've changed that keymap to using a list of app classes, to make it easier to add new ones later, if necessary.
> 
> ```python
> # new app classes show up on JetBrains apps installed via Snap
> jetbrains_lod = [
>     {clas:"^jetbrains-(?!.*toolbox).*$"                         },
>     {clas:"^jetbrains-webstorm$"                                },
>     {clas:"^jetbrains-phpstorm$"                                },
> ]
> 
> …
> 
> # }, when = matchProps(clas="^jetbrains-(?!.*toolbox).*$"))
> }, when = matchProps(lst=jetbrains_lod) )
> ```
> 
> Reinstalling should be safe as long as any customizations of the config file that should be retained are inside the "slice marks" comment lines.
> 
> Get the new zip file from here, it's a new branch for testing this change:
> 
> https://github.com/RedBearAK/toshy/tree/jetbrains_list_test

sure i'm testing right now

**Comment by RedBearAK** [comment]
I forgot that there is a "negative lookahead" matching pattern in the original condition: 

```py
}, when = matchProps(clas="^jetbrains-(?!.*toolbox).*$"))
```

This regex pattern should have already been matching on app classes like `jetbrains-phpstorm` or `jetbrains-webstorm`. Anything that starts with `jetbrains-` and doesn't contain `.*toolbox`. 

Which means that the change I made was meaningless and unnecessary, and if you were having trouble with the keyboard shortcuts in PhpStorm it is most likely because the keymap setting chosen inside the JetBrains app is not the one the original keymap in the Toshy config file was meant to work with. 

I don't use the JetBrains apps, so I'm not sure which internal keymap choice is the correct one. My locally installed PhpStorm is defaulting to the "GNOME" keymap. I'm not familiar with the normal shortcuts for JetBrains apps on macOS, so I can't really test the shortcuts in any meaningful way. 

Do you have a keymap besides "GNOME" selected in the settings in your JetBrains apps?

**Comment by MNhat0308** [comment]
> I forgot that there is a "negative lookahead" matching pattern in the original condition:
> 
> ```python
> }, when = matchProps(clas="^jetbrains-(?!.*toolbox).*$"))
> ```
> 
> This regex pattern should have already been matching on app classes like `jetbrains-phpstorm` or `jetbrains-webstorm`. Anything that starts with `jetbrains-` and doesn't contain `.*toolbox`.
> 
> Which means that the change I made was meaningless and unnecessary, and if you were having trouble with the keyboard shortcuts in PhpStorm it is most likely because the keymap setting chosen inside the JetBrains app is not the one the original keymap in the Toshy config file was meant to work with.
> 
> I don't use the JetBrains apps, so I'm not sure which internal keymap choice is the correct one. My locally installed PhpStorm is defaulting to the "GNOME" keymap. I'm not familiar with the normal shortcuts for JetBrains apps on macOS, so I can't really test the shortcuts in any meaningful way.
> 
> Do you have a keymap besides "GNOME" selected in the settings in your JetBrains apps?

Yeah i think so
I have tried and have  to map a lot of keymap again in config jetBrains
The reason i use ToShy , i want to use "alt" with mean "command" in all app include jetBrains

**Comment by RedBearAK** [comment]
>  The reason i use ToShy , i want to use "alt" with mean "command" in all app include jetBrains

That should be what it does in all apps, if you have a Windows (PC) keyboard. 

>  I have tried and have to map a lot of keymap again in config jetBrains

I'm not sure what you mean, but if you can reset the keymap to the defaults in JetBrains it should work. I'll contact the original author of the JetBrains keymap and see if they can remember which internal keymap JetBrains apps should use.

**Comment by MNhat0308** [comment]
> > The reason i use ToShy , i want to use "alt" with mean "command" in all app include jetBrains
> 
> That should be what it does in all apps, if you have a Windows (PC) keyboard.
> 
> > I have tried and have to map a lot of keymap again in config jetBrains
> 
> I'm not sure what you mean, but if you can reset the keymap to the defaults in JetBrains it should work. I'll contact the original author of the JetBrains keymap and see if they can remember which internal keymap JetBrains apps should use.

I make a copy keymap and remap it to my own 
and i change value and make it like my own jetbrains in my MacOS
![Screenshot from 2024-03-09 17-42-55](https://github.com/RedBearAK/toshy/assets/57012342/f54f9a77-50fb-47c8-9c97-20e5416ef645)

**Comment by RedBearAK** [comment]
The Toshy keymapper config is designed to overlay modifier remaps (one for "terminals" and one for "GUI" apps) and keymaps for specific apps, so that you don't need to modify the default shortcuts of any app like your JetBrains apps. 

Try setting the keymap to "GNOME". Custom keymaps in apps will never work correctly with the Toshy config. Because the keymapper will be remapping your shortcuts onto the wrong output shortcuts, and they won't match the custom keymap you created inside the app. 

Is Toshy making keyboard shortcuts work like you want in all other apps besides the JetBrains apps?

**Comment by MNhat0308** [comment]
i agree with you
but jetbrains has multiple keymap
i dont want to use default key map GNOME, i want to use keymap VSCODE(MACOS)

**Comment by RedBearAK** [comment]
If your custom keymap was already making all your shortcuts work like macOS (with Alt as Cmd) before you installed Toshy, and you don't want to try the "GNOME" keymap, you'll have to get Toshy to treat the JetBrains apps as part of the "remotes" group, where all the modmaps and general keymaps get disabled. This way Toshy won't interfere with your custom keymap. 

Look for these marks in your config file: 

```py
# Suggested location for customizing lists and variables for use with the "when" conditions.
###################################################################################################
###  SLICE_MARK_START: user_custom_lists  ###  EDITS OUTSIDE THESE MARKS WILL BE LOST ON UPGRADE



###  SLICE_MARK_END: user_custom_lists  ###  EDITS OUTSIDE THESE MARKS WILL BE LOST ON UPGRADE
###################################################################################################
```

Place this inside those marks: 

```py
# Suggested location for customizing lists and variables for use with the "when" conditions.
###################################################################################################
###  SLICE_MARK_START: user_custom_lists  ###  EDITS OUTSIDE THESE MARKS WILL BE LOST ON UPGRADE


remotes_lod.append({clas="^jetbrains-.*$"})


###  SLICE_MARK_END: user_custom_lists  ###  EDITS OUTSIDE THESE MARKS WILL BE LOST ON UPGRADE
###################################################################################################
```

Because it's inside the marks, this change will be protected. 

You will also need to change the condition on the "JetBrains" keymap in the Toshy config, and you will need to repeat this if you reinstall Toshy, because it won't be a protected change: 

```py
# Keybindings for IntelliJ
keymap("Jetbrains", {
...
# }, when = matchProps(clas="^jetbrains-(?!.*toolbox).*$"))
}, when = True is False )
```

This change to the condition should stop the whole "JetBrains" keymap in the Toshy config from ever becoming active. 

You could also just empty out or completely delete or comment-out the "JetBrains" keymap (or the things inside it), but you'd also have to repeat that if you reinstalled Toshy. 

Save the config file after making these changes, and restart Toshy. 

Toshy should now treat the JetBrains apps as if they are "remotes" and it will appear as if Toshy is disabled when using the JetBrains apps. Your custom internal keymap will take over entirely. If it worked before Toshy, it should work again, just like it did before. 

This isn't typically how Toshy is meant to be used, but it would seem to be your only choice to make it work with your custom JetBrains setup.

**Comment by MNhat0308** [comment]
I remap key after install toshy so all my remap wont work if dont have  toshy
I do it because i want it look like my jetbrains macos, but jetbrains ubuntu dont have option keymap VSCODE(MACOS)
By the way thanks to for supporting me

**Comment by RedBearAK** [comment]
Ok, so just delete or disable the JetBrains keymap in your Toshy config, but don’t do the “remotes” thing I suggested. 

Toshy will do the modifier remaps, then you can use the VSCode )macOS) custom keymap in JetBrains apps to get the Mac-like shortcuts. 

Maybe that will do what you want. But it still may not work like you expect. I can’t say for certain. 

Without more details it is hard to understand the specifics of how it isn’t working for you.

**Comment by MNhat0308** [comment]
Thanks for supporting
Have a good day!
