### ISSUE TITLE
(Question) Replace Cmd+Space shortcut on Gnome+Wayland?

### ISSUE THREAD

**Issue by a-plastic-bag** [RedBearAK/toshy#195]
I apologise if this is obvious, but I couldn't see how to do it in the config. 

The default for Toshy is to use Cmd+Space to open Gnome's application menu. 

However I've got an extension for a Spotlight-like search bar.  How would I go about unbinding Gnome's menu from Cmd+Space so I can bind my extension to it instead?

**Comment by RedBearAK** [comment]
@a-plastic-bag 

This one is always a little tricky. Usually I would advocate copying the keymap that is affecting your exact desktop environment and DE version, and setting up an override to make it do something else. You can see the keymap name when you use the shortcut after running the command `toshy-config-verbose-start` in a terminal. It will depend on the GNOME version. 

Place the copy of the keymap in the “User Apps” marked editable “slice” and then modify it to send the shortcut you assign to the extension. The keymapper operates like a keyboard, there’s no “binding” exactly. It will transform “RC-Space” into whatever keystrokes you specify. 

The reason for putting the new keymap in the “User Apps” section is so the change would be retained if you reinstall Toshy. Add something like “ - overrides” to the keymap name so that it is unique. 

I like to use Shift-RC-Space (Shift-Cmd-Space) to remap onto the original output shortcut to open the Overview, when I’m using an alternate launcher like Ulauncher with Cmd-Space (RC-Space in the config file). 

If you modify the config file of course you need to restart Toshy after saving the changes.

**Comment by RedBearAK** [comment]
@a-plastic-bag 

I wrote up a Wiki page that hopefully explains the process to set up an override of any kind of default shortcut, with the examples focusing on `Cmd+Space` since this is one that will commonly need to be tweaked by end users. I have an override myself, for using Ulauncher on GNOME. 

It may look complicated but I just made it very verbose with lots of examples to illustrate the process, which can be summed up as "make a copy of the relevant keymap, put it in a different spot, and then modify it and restart Toshy". Skim it and you'll probably get the idea. But the details matter. 

Let me know if anything needs to be clarified. 

https://github.com/RedBearAK/toshy/wiki/How-to-(persistently)-change-the-Cmd-Space-remap

**Comment by leejoramo-d51** [comment]
@RedBearAK  I have been following along with the activity on this project since I moved from Kinto to Toshy a few weeks ago. I just read your clear and articulate "Cmd Space remap" wiki. I want to thank you. 

Your GitHub Issue discussions are prompt and helpful. Your source code well commented and structured to easily navigate. 

This maybe one of the best documented and maintain open source projects  I have used in my decades of coding. Thank You for your efforts as a coder, writer and project manager. Simply Amazing.

**Comment by RedBearAK** [comment]
@leejoramo-d51 

I appreciate the sentiment more than you know. Another one to print out and frame on the wall. 🤣

Want to know the secret? I get easily confused and it helps to write a lot of things down. 🤣 🤣 🤣

Though, to be fair, trying to explain things to others is well-known to be a great way to learn things better yourself, and cement them in your memory. It's not a coincidence that the best teachers claim they learn from their students just as much as they teach. I happen to be one of my own best students. 🤣

Very kind words no matter what. ❤️ 👍🏽 

If you know anyone looking for a project manager that can work remotely, point them at me, maybe. 🤣

**Comment by a-plastic-bag** [comment]
Just tried it out. This solution works fantastic and the wiki was super easy to follow. Thanks so much for the help! Closing this issue now.
