### ISSUE TITLE
(Question) How to write "ç"?

### ISSUE THREAD

**Issue by hrqmonteiro** [RedBearAK/toshy#243]
I am on openSuse, and in my keyboard (which is us international layout), if i press right "alt gr" + "," it typed this character, with Toshy how can i do it?

**Comment by RedBearAK** [comment]
To get access to the ISO level 3 (and level 3 Shifted) characters on such a keyboard with the `Alt_Gr` key again, enable the "Alt_Gr on Right Cmd" option in the tray icon menu, under "Preferences". 

The same option can be found in the "Toshy Preferences" GUI app, if you are having any trouble getting the tray icon to appear. 

Changing these "preferences" doesn't require restarting the Toshy services. They become active "live". But if you made edits to the config file (like changing the suspend timeout setting), you will need to restart Toshy from the tray icon or using the `toshy-servics-restart` terminal command. 

Toshy does support a couple of US layouts for all the "special characters" that you get on macOS when holding down Option or Shift-Option, so "ç" would be on Option+C, and "Ç" is on Shift+Option+C. But if you are not used to using the standard US or "ABC Extended" layouts in macOS you would probably want to just use the instructions above and continue getting to those characters the way you are used to, with Alt_Gr. 

You may also want to entirely disable the Toshy special character layout in the "OptSpec Layout" submenu, if you don't find it useful. 

How well your keyboard layout will work with any shortcuts that the keymapper will find in the config file and transform (or macros of characters) will depend on how different your layout is from the standard US layout. The keymapper has some issues with non-US layouts, and the key definition file can be adjusted if necessary to overcome specific problems with some combos. 

Let me know if you run into other problems.

**Comment by RedBearAK** [comment]
@hrqmonteiro 

Note that the way Toshy does the special characters uses a Unicode keyboard shortcut that only works with `ibus` enabled as the input manager (or method?), and may produce a character that is technically not the same as the character you would normally get from your international keyboard layout. So the Toshy special characters are only useful in limited circumstances.

**Comment by hrqmonteiro** [comment]
> @hrqmonteiro
> 
> To get access to the ISO level 3 (and level 3 Shifted) characters on such a keyboard with the `Alt_Gr` key again, enable the "Alt_Gr on Right Cmd" option in the tray icon menu, under "Preferences".
> 
> The same option can be found in the "Toshy Preferences" GUI app, if you are having any trouble getting the tray icon to appear.
> 
> Changing these "preferences" doesn't require restarting the Toshy services. They become active "live". But if you made edits to the config file (like changing the suspend timeout setting), you will need to restart Toshy from the tray icon or using the `toshy-servics-restart` terminal command.
> 
> Toshy does support a couple of US layouts for all the "special characters" that you get on macOS when holding down Option or Shift-Option, so "ç" would be on Option+C, and "Ç" is on Shift+Option+C. But if you are not used to using the standard US or "ABC Extended" layouts in macOS you would probably want to just use the instructions above and continue getting to those characters the way you are used to, with Alt_Gr.
> 
> You may also want to entirely disable the Toshy special character layout in the "OptSpec Layout" submenu, if you don't find it useful.
> 
> How well your keyboard layout will work with any shortcuts that the keymapper will find in the config file and transform (or macros of characters) will depend on how different your layout is from the standard US layout. The keymapper has some issues with non-US layouts, and the key definition file can be adjusted if necessary to overcome specific problems with some combos.
> 
> Let me know if you run into other problems.

Well, i did that, but it is not working here.

To be more clear, my keyboard is the Keychron K3, and it has a switch to set it to mac-type keyboard or windows-type, i tried on both ways.

And also, on Toshy preferences i tried the Keyboard Type option on anything (Auto adapt, Apple, Windows etc)

I was not able to make the character with Shift + Option + C or anything else.

Any more help would be nice.

And i have ibus enabled indeed.

**Comment by RedBearAK** [comment]
> To be more clear, my keyboard is the Keychron K3, and it has a switch to set it to mac-type keyboard or windows-type, i tried on both ways.

For a switchable keyboard I usually recommend that it be kept in the Windows mode, and then it should be automatically seen as a Windows type by the Toshy config, since its name won't be found in the lists that would cause it to be treated as an Apple type (and it doesn't have "Apple" as part of its name). 

If you did set it to Mac mode, you'd need to use the "Apple" override in the tray icon menu, and put the device name in the custom dictionary in the config file, as described in the README. 

So if you have it in Windows mode and have the default "Auto-Adapt" selected, the modifier keys should be in the correct place, and you should find "Ç" on Shift+Option+C (which "Option" being the key in the place that key would normally be on an Apple keyboard). A PC keyboard will normally have the Meta/Super/Win key in that spot. 

Are other normal shortcuts like Cmd+Z/X/C/V/W/Q/A/T/R working the way you expect? The Cmd key equivalent on a PC keyboard is normally the key just to the left of the Space bar (Alt). It's the physical location that matters. 

Alt_Gr will also only work on the right side of the Space bar, just as it would without Toshy involved. 

> And i have ibus enabled indeed.

To check that the Unicode shortcut is actually working, do Shift+Cmd+U (if Toshy is enabled) or Shift+Ctrl+U (if Toshy is disabled). That should cause an underlined "u" to appear in any text field or editor, and then typing a Unicode address like "2014" and hitting Enter should produce a Unicode character. The code "e7" should make the small cedilla character. 

If none of this helps we may have to look at the log and verbose output to see what the problem is. 

You didn't say what your desktop environment is, just openSUSE, and whether you are in X11 or Wayland. 

The `toshy-env` command in a terminal should reveal all the necessary info. You can open the services log from the tray icon menu, and check `toshy-services-status` in a terminal. Two services should be active unless you are in a KDE Plasma Wayland session, then there should be three services active.

**Comment by hrqmonteiro** [comment]
Sorry for the delay, i was using Mac for a while

Right now, i reinstalled openSuse, am using it on Plasma Wayland and now it works perfectly by just setting the "Alt GR" option
