### ISSUE TITLE
[BUG] Holding Shift modifier repeats keycode instead of holding it

### ISSUE THREAD

**Issue by squk** [RedBearAK/toshy#26]
```
Bare metal or virtual machine: 
(If in VM, which VM software): None

(Try running 'toshy-env' in a terminal.)

                 DISTRO_NAME     = 'debian'
                 DISTRO_VER      = 'rodete'
                 SESSION_TYPE    = 'x11'
                 DESKTOP_ENV     = 'gnome'

Any DE(s) tried with Wayland?: 

Keyboard type (IBM, Chromebook, Windows, Apple):  Apple
Keyboard device name (try 'toshy-devices'):  LAZYDESIGNERS Bolt
```

Problem observed:  
* * *
Holding Shift repeats the key code rather than holding it. This makes it so multi-select doesn't work in the majority of GUI applications(i.e. filebrowswer, gmail, etc.)

**Comment by RedBearAK** [comment]
@squk 

I don't really understand this issue, but I'm interested to hear more about it. The keymappers (xkeysnail with Kinto and keyszer with Toshy) generally just accept what comes in and then send it out the virtual keyboard, transforming anything that is found in a `modmap` or `keymap`. And keys normally start sending repeat events (with the repeat delay and repeat rate governed by things like `xset`) when you hold them down, and the keymappers haven't been designed to block the repeat events. 

If you have some understanding of why it doesn't work with your apps, let me know. But are you sure you aren't bumping up against the `keyszer` "suspend" timeout, which defaults to 1 second? It's in the early part of the config file, and there's at least one FAQ entry about it. 

If the key seems to be repeating it should be because your real keyboard is sending "repeat" events at the set repeat rate. 🤷🏽‍♂️  That's about all I know about that side of things.

**Comment by RedBearAK** [comment]
If you still think this is an issue try submitting it to the `keyszer` issues: 

https://github.com/joshgoebel/keyszer/issues

**Comment by uriel-4** [comment]
If you press Key and then press Shift right away, Shift key press only reaches after 1-2 seconds, probably on repeat event of that Key. It doesn't happen without toshy services running.
Tested on my own GLFW based app. This is definitely not GLFW issue though, as it works correctly without toshy services running.

Also my MX Keys keyboard randomly shuts off every now and then, also definitely toshy services issue. Doesn't happen without toshy. 

OS: pop_os

**Comment by RedBearAK** [comment]
@uriel-4 

The first part is probably just the “suspend” timeout setting in the config file. Which is set by default to 1 second. Usually people count to 2 when trying to estimate how much time has passed. You can change the suspend delay in your config file. 

The second part sounds like it should be in a new issue. It may not be what you think. Open a new issue with output from the “toshy-debug” command copied from just before and during the time when the keyboard is acting strangely.

**Comment by uriel-4** [comment]
Why this suspend setting isn't lower than 1 second? Especially in games I think this scenario happens quite often. Setting to 0.1s definitely made it better, although it would be better to just send shift keypress event.

**Comment by RedBearAK** [comment]
> Why this suspend setting isn't lower than 1 second by default? Especially in games I think this scenario happens quite often. Setting to 0.1s definitely made it better, although it would be better to just send shift keypress event.

It’s an attempt to prevent issues like the Alt key causing menu focus stealing. Outside of the gaming scenario it’s pretty effective for a lot of users. If you really need it to react faster you can set the delay to zero.
