### ISSUE TITLE
How to uninstall Toshy+keyszer ?

### ISSUE THREAD

**Issue by sahfd4eiugf** [RedBearAK/toshy#27]
I have been using kinto on popos (ubuntu 22) for a while and decided to give Toshy a go
I am not fully ready to make the switch yet, and want to go back on kinto but it seems keyszer keeps launching in the background
Also my Super key doesn't open the search bar anymore ... it only works with the shortcut Super + /

**Comment by RedBearAK** [comment]
@sahfd4eiugf 

Uninstall function is incomplete, but there are a couple of "remove" scripts that will take care of most of it. Mainly this one will stop, disable and completely remove the "user" `systemd` services so they won't autostart at login: 

```sh
toshy-systemd-remove
````

And if you want to try Toshy again you can re-run the installer (which at this point shouldn't be clobbering any user customizations in the config file, if you stay within the "marks"), or you can just do the opposite command, which will put the services back, enable and start them: 

```sh
toshy-systemd-setup
```

I've designed these so that things can be turned on and off any number of times without causing any strange issues. 

The tray icon is started from a "desktop" file in the ~/.config/autostart folder, and you can either delete it from there with a file manager or it may show up in your DEs "Autostart" control panel, and you can just uncheck or remove it that way. 

If you want to make the desktop apps disappear you can do this: 

```sh
cd ~/.config/toshy/scripts
./toshy-desktopapps-remove.sh
```

And then you can remove all the CLI commands if you really want to with: 

```sh
cd ~/.config/toshy/scripts
./toshy-bincommands-remove.sh
```

The Super key is disabled for opening the overview because it's a weird behavior for a modifier key coming from macOS. Kinto does the same thing. There is a FAQ entry about re-enabling it. It's a simple command. 

https://github.com/RedBearAK/toshy#gnome-and-the-metasuperwincmd-key-overlay-key

Actually if you run the installer with the `--remove-tweaks` option that will theoretically re-enable it too, but I haven't done a lot of testing on that part of the installer yet. 

Thanks for trying Toshy out for a bit. I'm trying to make it as universal and user-friendly as possible.

**Comment by RedBearAK** [comment]
@sahfd4eiugf 

Uninstall function/option is now available: 

```sh
./toshy_setup.py --uninstall
```
