### ISSUE TITLE
[BUG] Cmd+Dot conflcts with VsCode quickfix

### ISSUE THREAD

**Issue by wtdcode** [RedBearAK/toshy#33]
Bare metal or virtual machine: Bare metal
(If in VM, which VM software): None

(Try running 'toshy-env' in a terminal.)

Linux distro name: KUbuntu
Distro version: 2304
X11/Xorg or Wayland: X11 
Desktop environment(s): KDE

Any DE(s) tried with Wayland?: No 

Keyboard type (IBM, Chromebook, Windows, Apple): Apple
Keyboard device name (try 'toshy-devices'): /dev/input/event3    SONiX USB DEVICE                    usb-0000:34:00.4-2/input0

These terminal commands may provide helpful info:

- toshy-services-log  
- toshy-services-status  
- toshy-config-start-verbose  
- toshy-devices
- toshy-env

Problem observed:  

```
(DD) WM_CLASS: 'Code' | WM_NAME: 'xxxx - Visual Studio Code'
(DD) DEVICE: 'SONiX USB DEVICE' | CAPS_LOCK: 'False' | NUM_LOCK: 'True'
(DD) ACTIVE KEYMAPS:
     'User hardware keys', 'VSCodes overrides for not Chromebook/IBM',
     'VSCodes', 'Cmd+Dot not in terminals', 'GenGUI overrides: not Chromebook',
     'GenGUI overrides: Ubuntu', 'GenGUI overrides: KDE', 'General GUI',
     'Diagnostics'
(DD) COMBO: RCtrl-DOT => ESC in KMAP: 'Cmd+Dot not in terminals'
```

This mapping interferes with vscode internal quick fix shortcut: `ctrl+.` and at this moment I remove these lines as a workaround:

```python
# Note: terminals extends to remotes as well
# keymap("Cmd+Dot not in terminals", {
#     C("RC-Dot"):                C("Esc"),                       # Mimic macOS Cmd+dot = Escape key (not in terminals)
# # }, when = lambda ctx: ctx.wm_class.casefold() not in terminals)
# # }, when = matchProps(not_clas=termStr_ext) )
# }, when = matchProps(not_lst=terminals_and_remotes_lod) )
```
Not sure if there is a better way?

**Comment by RedBearAK** [comment]
So here's the main question. Does that shortcut actually work on VSCode on macOS? I kind of doubt it, because as far back as classic Mac OS they've been using Cmd+Dot to "cancel" things like dialogs. And when OS X came along they extended it into the Terminal, where it performs the same as Ctrl+C (SIGINT). Everywhere else it just acts like you hit Escape. 

Rather than removing those lines entirely you can simply override the behavior of Cmd+Dot when you are in VSCode(s), by having a line in the main VSCode(s) keymap that just remaps that shortcut back to the same keys. 

Look for this keymap and add the line to override Cmd+Dot: 

```py
keymap("VSCodes", {
    # C("Super-Space"):           C("LC-Space"),                  # Basic code completion (conflicts with input switching)
    C("RC-Dot"):                C("RC-Dot"),                       # Override Cmd+Dot system shortcut for QuickFix
```

Doing an override like this just for one application will leave the general Cmd+Dot shortcut working everywhere else. You can override things in any keymap that is also active for the same application and defined further down in the config file. The remap that gets encountered in memory first is the one that gets used by the keymapper. 

And, as you can see the remap for Super+Space (physical Ctrl+Space) for code completion in VSCode is also commented out, since that is used in macOS for input switching of keyboard layouts, so that doesn't actually work in macOS VSCode. If switching of keyboard layouts is not something you need, you can re-enable that too. 

Unless you can confirm that Cmd+Dot actually works for QuickFix in VSCode on macOS, it would be against the main purpose of Toshy to put that in the default config. These are probably customizations that you will need to keep track of and merge back in by hand if you ever run the installer again. It will get overwritten since it's not in one of the special "protected" sections of the file. 

Although I might be convinced to add this override to that keymap in commented-out form, so that it's easier to re-enable.

**Comment by RedBearAK** [comment]
> I'm pretty sure it works because it's one of my daily shortcuts.

Really. On macOS? I'll have to get to one of my remaining Macs and try it out. If it works like you say, without some sort of special trick to get it to override the global shortcut, then we can add it to the default config.

**Comment by wtdcode** [comment]
> > I'm pretty sure it works because it's one of my daily shortcuts.
> 
> Really. On macOS? I'll have to get to one of my remaining Macs and try it out. If it works like you say, without some sort of special trick to get it to override the global shortcut, then we can add it to the default config.

This is especially useful when writing rust because `Cmd+.` completes the missing imports automatically. At this moment I don't have a mac to verify it but I'm pretty sure. For reference, see this dummy question:

https://stackoverflow.com/questions/47287367/what-is-the-keyboard-shortcut-in-visual-studio-code-to-pop-up-the-quick-fix-menu

**Comment by RedBearAK** [comment]
Well, I was able to get on a Mac mini running Big Sur and download the latest VSCode for macOS. And your QuickFix shortcut indeed works. 

I guess I will add it to the default config, and try to remember to put a PR for it in for Kinto too. (Done: https://github.com/rbreaves/kinto/pull/816)

**Comment by RedBearAK** [comment]
Added to the default config in the main branch, so this shouldn't be a problem anymore. 

https://github.com/RedBearAK/toshy/commit/4990b51cce4378dbc6ae3ee94e6fd1c143062452

If you consider this resolved feel free to close this issue. Open a new one if anything else comes up. Thanks for the input!
