### ISSUE TITLE
Option+click doesn't jump cursor in terminal

### ISSUE THREAD

**Issue by zadeviggers** [RedBearAK/toshy#340]
**Is your feature request related to a problem? Please describe.**
On Macos, I can jump my cursor to a particular spot in the current command I'm writing in my terminal (iterm) by option+clicking on the spot I want to move it to.

**Describe the solution you'd like**
Add support for jumping the cursor in Konsole using option+click.

**Describe alternatives you've considered**
The built-in click to jump option in Konsole. This doesn't seem to work at all (with or without option), and requires setting up a profile to configure.

**Additional context**
KDE 6.1 Fedora 40 Asahi Linux on M2 Macbook air.

**Comment by RedBearAK** [comment]
I will look into it, but I think this is something that would need to be a feature of the application itself. Toshy is mostly limited to sending keystrokes. Only the app window would know where you clicked and be able to move the cursor to that location in the command. 

Wordwise terminal shortcuts should work, so at least the cursor can move to beginning or end, or word boundaries.

**Comment by RedBearAK** [comment]
@zadeviggers 

> The built-in click to jump option in Konsole. This doesn't seem to work at all (with or without option), and requires setting up a profile to configure.

Can you tell me where you found a setting like that? I can't find anything like it in the general or profile settings.

**Comment by zadeviggers** [comment]
@RedBearAK Settings > configure konsole > profiles > choose an existing profile or make a new one (the default one is read only) >  semantic integration > mouse click in input line

**Comment by RedBearAK** [comment]
I see it now. That option also doesn't seem to do anything for me. But that is most likely what you would need in order to mimic the feature in iTerm2. Although it doesn't appear to ask for any kind of modifier key. 

It doesn't work with Toshy enabled or with Toshy stopped, which means Toshy isn't interfering, and you should probably file a bug report with KDE to get the feature working. 

I don't know that there is anything Toshy can do to enable a feature like this. The keymapper can apply modifier remaps and key/combo remaps for all apps, app groups and specific apps, and that's about it. It's literally just a virtual keyboard device. If you can't do something with your real keyboard, the keymapper can't do it either. 

Let me know if you encounter anything else that isn't working as expected.

**Comment by zadeviggers** [comment]
Sweet I'll look into doing that. It's probably an issue with the Fedora distribution to be honest, but same general thing.
