### ISSUE TITLE
KDE Move Window Modifier

### ISSUE THREAD

**Issue by 51n7** [RedBearAK/toshy#35]
```
Bare metal

Linux distro name: Neon 22.04
Distro version: X11
Desktop environment(s): KDE

Keyboard type (IBM, Chromebook, Windows, Apple): 
Windows
```

With KDE I am able to hold `super/meta` and drag anywhere in a window to move it around but with Toshy active I loose this functionality. A possible [solution](https://github.com/rbreaves/kinto/issues/590#issuecomment-1151719401) was mentioned in [Kinto](https://github.com/rbreaves/kinto) by changing the modifier key to move a window but this is not currently working with Toshy.

I understand this might be out of scope for what Toshy is supposed to achieve as what I'm asking for would create a Mac/KDE hybrid so if this ask gets shut down I can live with that. A little sadness but I'll live.
* * *

**Comment by RedBearAK** [comment]
Question: Using a trackpad/touchpad device? Have you tried changing the "suspend" timer? 

I had myself pretty confused by seeing inconsistent behavior from changing the drag key from `Meta` to `Alt` in "Window Behavior -> Window Actions", but I think most of the problem was forgetting to set the suspend timer length in the Toshy config file to zero or 0.1 seconds. The suspend timer will interfere with all kinds of Mod+click actions if you are using a touchpad device, because the click is not detected the same way as a mouse click. 

Before changing anything, you can try holding the modifier key for at least one second before trying to drag the window. The cursor should change to the four-way cursor when the suspend timer ends, if you've changed the drag key to `Alt` and you're holding down the key at the "Option" key position. 

Here's more about the `keyszer` suspend timer, and how to change it: 

https://github.com/RedBearAK/toshy#touchpadstrackpads-and-keyszer-suspend-timer

Let me know if that helps get the Mod+drag function back. 

Of course you may then have issues with certain apps letting the menu bar grab keyboard focus when you use the Alt key, so refer to the workarounds in the next FAQ entry: 

https://github.com/RedBearAK/toshy#vscodes-and-firefox-menu-stealing-focus-when-hitting-optionalt

**Comment by RedBearAK** [comment]
To clarify, changing the drag key in KDE settings from `Meta` to `Alt` is only necessary to make it work in terminal apps where the Meta key is gone, but it will also have the side effect of keeping the function on the same physical key (on PC keyboards) that it was on before you started using Toshy. 

If you don't reduce the suspend timer, or disable it, you can also see a confusing phenomenon where both the physical Alt key and the physical Meta/Super/Win key will work for Mod+drag (on windows that are not terminals). This is because when the modifier is suspended by `keyszer`, the window manager can actually see "Alt" when you press the Alt key, but it will also see "Alt" when you press the Meta key. Kind of depends on how long you hold the key down. 

This effect basically disappears when you cut down the suspend timer far enough. The window manager won't have enough time to "see" the wrong key code before you click. By that time KWin will only be seeing the modmapped key. So the reaction will make a lot more sense. 

If it weren't for the problems with certain apps seeing keys like "Alt", I'd recommend everyone disable the suspend timer. But it can be useful. Especially if you never use a touchpad.

**Comment by jonbestdev** [comment]
Thanks for the detailed responce! Holding the modifier key does work so the suspend timer was the problem however I'm not using a trackpad/touchpad device so not sure why I would need to lower that, I'm just using a [mini desktop](https://store.minisforum.com/products/um350) with standard keyboard/mouse. I'll live with adjusting the suspend and see how it goes with various apps.

**Comment by RedBearAK** [comment]
Slightly odd. But I think the other thing that can happen is the mouse device is not "grabbed" by `keyszer` when it starts up, in which case I think it would not "see" the click event and release the modifier suspension, which is kind of what it supposed to happen. 

I still don't know all that much about that side of things, just that my touchpad has always required almost completely disabling the suspend timer. 

You'd be able to see which devices are grabbed in the initial output from `toshy-config-start-verbose` (or alternately `toshy-config-verbose-start` if you re-install from a future release of Toshy that I'm working on). If the mouse is not one of the devices that gets grabbed, that's probably the issue.

**Comment by 51n7** [comment]
I switched to an Apple keyboard (which I'll be using from now on) and updated to the latest version of toshy. Still the same problem if I have `suspend = 1` but I was able to use `toshy-config-start-verbose` to get the following output, does this help?
```
keyszer v0.6.92
(DD) CONFIG: /home/{user}/.config/toshy/toshy_config.py
(DD) THROTTLES: Pre-key: 12ms, Post-key: 18ms

(CG) Current settings:
        calling_module      = toshy_config.py
        db_file_path        = /home/{user}/.config/toshy/toshy_user_preferences.sqlite
        gui_dark_theme      = True
        -------------------------------------------
        optspec_layout      = 'US'
        forced_numpad       = True
        media_arrows_fix    = False
        multi_lang          = False
        Caps2Cmd            = False
        Caps2Esc_Cmd        = False
        Enter2Ent_Cmd       = False
        ST3_in_VSCode       = False
        -------------------------------------------

(CG) Toshy config sees this environment:
        DISTRO_NAME      = 'neon'
        DISTRO_VER       = '22.04'
        SESSION_TYPE     = 'x11'
        DESKTOP_ENV      = 'kde'

(DD) ENVIRON: Session type: 'x11', Desktop env: 'None'
(--) WATCH: Watching for new devices to hot-plug.
(--) Autodetecting all keyboards (--device not specified)
(+K) Grabbing 'Apple Inc. Magic Keyboard with Numeric Keypad' (/dev/input/event3)
(--) Ready to process input.

(II) in LEFT_CTRL (press)
(DD) KBTYPE: 'Apple' | Regex matched for device: 'Apple Inc. Magic Keyboard with Numeric Keypad'
(DD) modmap: LEFT_CTRL => LEFT_META [Cond modmap - GUI - Mac kbd]
(DD) on_key LEFT_META press
(DD) suspending keys [LSuper<Key.LEFT_META>]

(II) in LEFT_CTRL (release)
(DD) on_key LEFT_META release
(DD) resume because of mod release
(DD) resuming keys: [<Key.LEFT_META: 125>]
(OO) press LEFT_META 1688617267.24475
(OO) release LEFT_META 1688617267.2448473
```
There's no log from mouse click and and I dont see anything about `keyszer` grabbing my mouse here unless I captured the wrong output.

Side note though I'm not having any issue with `suspend = 0.1` which is probably because I'm using a global menu so `alt/option` cant focus the file menu so at this point it's not really an issue for me but more for curiosity.

**Comment by RedBearAK** [comment]
I may have been misunderstanding why `keyszer` has some code to make sure that it passes through mouse event codes, I think it might mainly be applicable to combined keyboard/mouse devices that use a USB dongle (for instance) or keyboards that actually have some mouse buttons integrated (like Logitech MX, I think). 

I'm not an expert on that side of things, like exactly how the suspend/resume is supposed to work. And don't think there would be mouse events in the logging even for devices that do get grabbed by `keyszer`. The logging is much more focused on what's happening with the keyboard. 

> Side note though I'm not having any issue with suspend = 0.1 which is probably because I'm using a global menu so alt/option cant focus the file menu so at this point it's not really an issue for me but more for curiosity.

Yeah, if you've got a situation like that where the Alt key isn't going to cause the keyboard focus to jump to the menu bar in apps like VSCode or Firefox, you should be good. Those are actually the only apps I've used where that problem cropped up. 

I guess you're basically just going to need to keep the suspend set to zero or 0.1 for your Mod+clicking to make sense. Why this is a problem while using a mouse is a mystery to me, but I've only worked on a couple of small features in `keyszer`. And the stuff that was needed to support Wayland+GNOME and Wayland+KDE. That had very little to do with the actual keymapping parts of the code. 

Thanks for the Ko-Fi, and let me know if you run into any other issues.

Feel free to close this issue if you think it's been solved as well as it can be.

**Comment by 51n7** [comment]
Yeah I think this can close now and the Ko-Fi was the least I could do, it seems whenever I look for a Mac to Linux issue you're already on it.
