### ISSUE TITLE
[BUG] Swapping grave and section keys

### ISSUE THREAD

**Issue by raraz15** [RedBearAK/toshy#359]
```
Bare metal or virtual machine: 
(If in VM, which VM software): Bare metal

(Try running 'toshy-env' in a terminal to fill out the following fields...)

		 DISTRO_ID       = 'ubuntu'
		 DISTRO_VER      = '24.04'
		 VARIANT_ID      = 'notfound'
		 SESSION_TYPE    = 'x11'
		 DESKTOP_ENV     = 'gnome'
		 DE_MAJ_VER      = '46'

Keyboard type (IBM, Chromebook, Windows, Apple): Apple
Keyboard device name (try 'toshy-devices'): Magic Keyboard
```

* * *

I want to swap the ` (grave) key and the § (section key). So I modified `toshy-main/keymapper-temp/src/xwaykeyz/models/key.py` in the following way.

```
    #GRAVE = 41
    GRAVE = 86

    #KEY_102ND = 86
    KEY_102ND = 41
```

Then I restarted my system, but the keys are functioning the same way. Is it because I did not re-install toshy? Or is there something else?

**Comment by RedBearAK** [comment]
@raraz15 

Modifying the file in that location won't work. You have to modify the one that gets installed in the Python virtual environment folder. That temporary folder gets deleted each time you run the installer, and re-cloned from GitHub. Changes you make there won't end up in the installed file. 

The location of that file varies depending on the version of Python used to create the `venv`. On my system with Python 3.12 the path is like this:

```
~/.config/toshy/.venv/lib/python3.12/site-packages/xwaykeyz/models/key.py
```

Whatever changes you make, you'll want to keep a backup of the modified `key.py` file, somewhere outside of `~/.config/toshy/`. It would get wiped out if you reinstalled Toshy. The installer makes a whole new `~/.config/toshy/` folder and Python virtual environment each time. (But the installer backs up and restores your specific config file customizations and preference settings.)

The changes you attempted look correct for what you're trying to accomplish. 

Let me know if you can't get it working.

**Comment by RedBearAK** [comment]
Also after editing the file all you need to do is restart the Toshy services from the tray icon, or the Preferences app, or from the terminal with `toshy-services-restart`.

**Comment by raraz15** [comment]
Thanks for the amazing repository and the response. In my system the python environment was also installed in `~/.config/toshy/.venv/lib/python3.12/site-packages/xwaykeyz/models`

So I made the changes i mentioned before on the `key.py` file here.

I first tried `toshy-services-restart` and the changes did not take effect. Then I restarted my machine and still no effect.

What might be the problem here?

**Comment by RedBearAK** [comment]
Restarting the system is really not necessary. It’s just a user process. 

Try looking at the debugging output in the terminal. 

`toshy-debug`

Older installs of Toshy will need to use a different alias: 

`toshy-config-verbose-start`

Tap the two keys and see what the log says they are. 

When Toshy is disabled, the section symbol comes out when you press the 102nd key? What keyboard layout are you using?

**Comment by raraz15** [comment]
When Toshy is disabled pressing the section key produces the 102nd key and vice versa.

I see the problem now looking at the `toshy-debug` outputs.

```
(II) in GRAVE (press)
(CX) CTX_X11: Using Xlib for window context
(DD) on_key GRAVE press
(DD) KBTYPE: 'Apple' | WARNING: Override applied! Dev: 'Apple Inc. Magic Keyboard'
(OO) press GRAVE 1722933272.2833982
§
(II) in GRAVE (release)
(CX) CTX_X11: Using Xlib for window context
(DD) on_key GRAVE release
(OO) release GRAVE 1722933272.385737

(II) in KEY_102ND (press)
(CX) CTX_X11: Using Xlib for window context
(DD) on_key KEY_102ND press
(DD) KBTYPE: 'Apple' | WARNING: Override applied! Dev: 'Apple Inc. Magic Keyboard'
(OO) press KEY_102ND 1722933275.007474
`
(II) in KEY_102ND (release)
(CX) CTX_X11: Using Xlib for window context
(DD) on_key KEY_102ND release§`asda
(OO) release KEY_102ND 1722933275.069254
```

I am using an Apple Magic keyboard with ISO English International layout. https://support.apple.com/en-us/102743
How can we disable the Override behavior?

I set the `keyboard-type` parameter of toshy to auto-adapt*, restarted tosh services from the GUI  and re-tired, no change. Before the keyboard-type was set to apple.

**Comment by RedBearAK** [comment]
The keyboard type should be left on Auto-Adapt if the keys next to the Space bar seem like they are in the right place to behave like an Apple keyboard does on macOS. The type is really only about the two keys next to the Space bar. Any keyboard with "Apple" in the device name should automatically be treated like an Apple keyboard. 

Leaving the setting on Auto-Adapt will let you use other types of keyboards on the same system and have them be treated as the correct type as well, at the same time. Without needing to mess with the keyboard type setting. 

But this problem with not being able to swap the keys is strange. I'm wondering what you are expecting to happen. 

I think maybe I was misunderstanding what you were trying to do. Changing key definitions in `key.py` will affect how the keymapper will react to the keys when used as part of a key or combo that gets remapped somehow in the config file. This is essential in some cases, like when you have an AZERTY keyboard instead of QWERTY, and you want Cmd+Q and Cmd+A to behave normally, instead of acting like they are swapped. 

But in this case what I think you're trying to accomplish is to literally swap the identity of the two keys, for general use. You want to fool your input system into thinking you typed the other key. This is different. I think what you want is a `modmap`, and you can put it in the config file, in the marked `user_custom_modmaps` slice so that it will survive a Toshy reinstall. 

```py
# Suggested location for adding custom modmaps for personal use.
###################################################################################################
###  SLICE_MARK_START: user_custom_modmaps  ###  EDITS OUTSIDE THESE MARKS WILL BE LOST ON UPGRADE

modmap("Cond modmap - User overrides",{
    # Swap Grave and KEY_102ND keys identities
    Key.KEY_102ND:              Key.GRAVE,
    Key.GRAVE:                  Key.KEY_102ND,
}, when = lambda ctx:
    cnfg.screen_has_focus and
    matchProps(not_clas=remoteStr)(ctx)
)

###  SLICE_MARK_END: user_custom_modmaps  ###  EDITS OUTSIDE THESE MARKS WILL BE LOST ON UPGRADE
###################################################################################################
```

Modmaps are often used to move modifier keys, but can be used to change any key into another key. With this example `modmap`, the shell and applications should receive Grave when you press the Section key, and Section when you press the 102nd key. 

I think for this to make sense, the changes in `key.py` need to be reverted to the defaults. But I'm not entirely sure about that. There's sort of more than one thing going on here, especially if you use the Cmd+Grave shortcut to do in-app window switching. After the `modmap` swap, the Section key should literally "become" a Grave key, as far as the keymapper is concerned. 

Get back to me after you try this. See how it works out.

**Comment by raraz15** [comment]
Thanks a lot! 

Just pasting your first suggestion rendered the keyboard useless, but after adding the second suggestions my keyboard is working as intended (in the Linux terminal) and the section and grave keys are swapped.

Also, in VsCode I can use the ctrl+` shortcut to open the terminal.
