### ISSUE TITLE
[BUG] Satechi keyboard for Macs not treated as "Apple" type

### ISSUE THREAD

**Issue by zachfeldman** [RedBearAK/toshy#377]
```
Bare metal or virtual machine: 
(If in VM, which VM software): None

(Try running 'toshy-env' in a terminal to fill out the following fields...)

Linux distro name: Ubuntu
Distro version:  24.04
Distro variant: N/A
X11/Xorg or Wayland: Wayland
Desktop environment(s): GNOME
DE version(s): ?

Keyboard type (IBM, Chromebook, Windows, Apple): Apple
Keyboard device name (try 'toshy-devices'): ?
```

* * *

Problem observed:

I've noticed that with two different keyboards I have with "Mac-like" design, Toshy doesn't always recognize them.

One is a Leopold FC660C with a command key grafted on to the alt key, so that's 100% expected for me.

But the other one is a Satechi keyboard with a dedicated command key, this one: https://www.amazon.com/gp/product/B081P1SRXM/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&psc=1

As requested, filing this issue for tracking!

**Comment by RedBearAK** [comment]
@zachfeldman 

Hey, Zach, thanks for stopping by to make a report. 

OK, the Satechi does look like finally a good candidate for automatically being treated as the "Apple" type, since it's a Mac-only design with the keys in the correct place for that. 

But I'll need some clarification on some things. 

> One is a Leopold FC660C with a command key grafted on to the alt key, so that's 100% expected for me.

The Leopold appears to have DIP switches for potentially converting the modifier locations. This is pretty common in the higher-end customizable mechanical keyboards. I recommend keeping those set to the "PC" position so that the key next to the Space bar keeps emitting the `Alt` key code. If Toshy is in the auto-adapt mode the keyboard should act like an Apple keyboard, which will make the swapped key caps make perfect sense, as long as Toshy is enabled. 

On the other hand if you've tried to tell the desktop environment that the Leopold is an Apple keyboard (independently from Toshy's config), that would throw things off. 

For keyboards to get treated as the "Apple" type there is a list in the default config file that is fairly short so far: 

```py
keyboards_Apple = [
    # Add specific Apple/Mac keyboard device names to this list
    'Mitsumi Electric Apple Extended USB Keyboard',
    'Magic Keyboard with Numeric Keypad',
    'Magic Keyboard',
    'MX Keys Mac Keyboard',
]
```

To add the Satechi to this default list I would need to know the device name (not the path). It should show up in the output from the `toshy-devices` command. Try to see if it also has a different device name when connected via the USB cable. Or Bluetooth, if you're already using USB. The two methods will usually show up as distinct device names. 

If you had the Leopold DIP switches in the "Mac" mode (again, not really recommended because then you'd have to do this) you would need to add it into this structure: 

```py
###################################################################################################
###  SLICE_MARK_START: kbtype_override  ###  EDITS OUTSIDE THESE MARKS WILL BE LOST ON UPGRADE

keyboards_UserCustom_dct = {
    # Add your keyboard device here if its type is misidentified.
    # Valid types to map device to: Apple, Windows, IBM, Chromebook (case sensitive)
    # Example:
    'My Keyboard Device Name': 'Apple',
    'Leopold Keyboard Device Name': 'Apple',
}

###  SLICE_MARK_END: kbtype_override  ###  EDITS OUTSIDE THESE MARKS WILL BE LOST ON UPGRADE
###################################################################################################
```

I assume since you didn't say anything about the device name that you might not be familiar with this structure in the config file, and are using the temporary forced override in the tray icon menu. That's really only supposed to be used while you set up the override for the specific device in the config file. The override structure allows the auto-adaptation to continue to work for all other connected keyboards.

**Comment by zachfeldman** [comment]
Thanks @RedBearAK ! Sorry for the false alarm, I realized that I actually disposed of that Satechi keyboard a few weeks ago because the battery went bad. So sadly I can't test on that one.

The leopold is I believe still set up in PC mode so sounds like it should be working. I will re-test (it's hooked up to a different machine) and let you know if I have any other issues!

Here is the output from that machine for the command you mentioned with the Leopold hooked up:
```
game@game-laptop:~$ toshy-devices

List of devices seen by the keymapper (xwaykeyz or keyseyer):

xwaykeyz v1.3.1
+-------------------------+-----------------------------------+-----------------------------------+
|         Device          |               Name               |               Phys               |
+-------------------------+-----------------------------------+-----------------------------------+
| /dev/input/event18       | XWayKeyz (virtual) Keyboard       | py-evdev-uinput                  |
| /dev/input/event17       | HDA Intel PCH HDMI/DP,pcm=8       | ALSA                             |
| /dev/input/event16       | HDA Intel PCH HDMI/DP,pcm=7       | ALSA                             |
| /dev/input/event15       | HDA Intel PCH HDMI/DP,pcm=3       | ALSA                             |
| /dev/input/event14       | HDA Intel PCH HDMI/DP,pcm=2       | ALSA                             |
| /dev/input/event13       | HDA Intel PCH Headphone           | ALSA                             |
| /dev/input/event12       | HDA Intel PCH Mic                 | ALSA                             |
| /dev/input/event11       | Video Bus                         | DP-2/input0                      |
| /dev/input/event19       | HID Keyboard HID Keyboard Consumer Control | LNXVIDEO/video/input0     |
| /dev/input/event10       | HID Keyboard HID Keyboard System Control | usb-0000:00:14.0-6.2/input1 |
| /dev/input/event9        | HID Keyboard HID Keyboard System Control | usb-0000:00:14.0-6.2/input0 |
| /dev/input/event8        | PixArt USB Optical Mouse          | usb-0000:00:14.0-6.1/input0      |
| /dev/input/event7        | ImExPS/2 Generic Explorer Mouse   | isa0060/serio1/input0            |
| /dev/input/event6        | FRMW0001:00 32AC:0006 Consumer Control | i2c-FRMW0001:00             |
| /dev/input/event5        | FRMW0001:00 32AC:0006 Wireless Radio Control | i2c-FRMW0001:00             |
| /dev/input/event4        | AT Translated Set 2 keyboard      | isa0060/serio0/input0            |
| /dev/input/event3        | Power Button                      | PNP0C0C/button/input0            |
| /dev/input/event0        | Lid Switch                        | PNP0C0D/button/input0            |
+-------------------------+-----
```

in case that's helpful!

**Comment by RedBearAK** [comment]
Well, that's a very generic device name, for what I assume is the Leopold keyboard: 

```
HID Keyboard HID Keyboard System Control
```

Too bad about that Satechi. There aren't that many Mac-only third-party keyboards. Would be nice to get more reports about those so the Toshy config could treat them correctly by default. 

As for the Leopold, the only good reason to switch it to the Mac mode might be if you were using it with both macOS and a PC, or dual-booting macOS and Linux on a Mac. In which case it might be convenient to avoid messing with the modifier location settings in macOS, and just have it work like an Apple keyboard as far as macOS is concerned. Then you'd need to "fix" it in the Toshy config like this: 

```
###################################################################################################
###  SLICE_MARK_START: kbtype_override  ###  EDITS OUTSIDE THESE MARKS WILL BE LOST ON UPGRADE

keyboards_UserCustom_dct = {
    # Add your keyboard device here if its type is misidentified.
    # Valid types to map device to: Apple, Windows, IBM, Chromebook (case sensitive)
    # Example:
    'My Keyboard Device Name': 'Apple',
    'HID Keyboard HID Keyboard System Control': 'Apple',
}

###  SLICE_MARK_END: kbtype_override  ###  EDITS OUTSIDE THESE MARKS WILL BE LOST ON UPGRADE
###################################################################################################
```

But outside of that circumstance of mixing macOS and Linux, the Leopold (in the PC mode) should definitely seem to have its modifier keys in the right place when Toshy is enabled. If that is not the case, we should look at that. 

The only thing I can think of that could cause the Leopold to not seem to work as expected is that you might have been using the forced "Apple" setting in the tray icon menu to fix the Satechi, and that would then cause the Leopold to also be treated like an "Apple" keyboard, which would reverse the virtualized Command and Option key locations on the Leopold. That option in the tray icon menu is a forced "all devices are this type" override.

**Comment by zachfeldman** [comment]
I went back to do some re-testing and I can no longer reproduce any issue with the Leopold!

Going to close this for now but will re-open if the issue I saw comes back. Thanks for looking @RedBearAK !

**Comment by RedBearAK** [comment]
> can no longer reproduce any issue with the Leopold

Always like to hear that! See you next time. 
👍
