### ISSUE TITLE
Option + Tab / Backspace not consistently recognized via WezTerm and Neovim

### ISSUE THREAD

**Issue by hugegulp** [RedBearAK/toshy#385]
Hi there, I am trying to get my neovim setup working again. I have option+tab (alt+tab) configured to run a function in neovim, and option+backspace (alt+backspace) to delete word (in insert mode). I use these two keybindings a lot. I am noticing that with Toshy enabled, I can't access either of these two key combinations. Especially while in WezTerm. I see a few FAQ entries about the option key, I'm assuming there's some oddness with it since there's remapping happening. But I'm not sure if there's something preventing the usage of the alt+tab key or the alt+backspace key here. Any help would be greatly appreciated! :pray:

**Comment by RedBearAK** [comment]
@hugegulp 

Hey, we're having major issues with internet in my region, so sorry if this is delayed or I don't comment again soon. The connection is still not working well, and has been broken for days. 

The `Alt+Tab` issue is no great mystery, since it's blocked in the default config, mostly to avoid confusion with the virtualized `Cmd+Tab` operation. Things can get a bit confusing depending on the keyboard type. That blocking can be overridden in the `user_apps` editable slice relatively easily, in your Toshy config file. You can open the Toshy config folder from the tray icon menu, normally, and the file to edit is `~/.config/toshy/toshy_config.py`. (Don't touch the files in the `~/.config/toshy/default-toshy-config/` folder, those are backups.) 

I think this would be the way to implement that: 

```py
####################################  USER APPS  #####################################
###                                                                                ###
###                                                                                ###
###      ██    ██ ███████ ███████ ██████       █████  ██████  ██████  ███████      ###
###      ██    ██ ██      ██      ██   ██     ██   ██ ██   ██ ██   ██ ██           ###
###      ██    ██ ███████ █████   ██████      ███████ ██████  ██████  ███████      ###
###      ██    ██      ██ ██      ██   ██     ██   ██ ██      ██           ██      ###
###       ██████  ███████ ███████ ██   ██     ██   ██ ██      ██      ███████      ###
###                                                                                ###
###                                                                                ###
######################################################################################
### This is a good location in the config file for adding new custom keymaps for 
### user applications and custom function keys. Watch out that you don't override 
### any "general" shortcuts like Cmd+Z/X/C/V that may be defined below this section. 
### Changes made between the "slice" marks will be retained by the Toshy installer 
### if you reinstall and it finds matching start/end markers for each section. 

###################################################################################################
###  SLICE_MARK_START: user_apps  ###  EDITS OUTSIDE THESE MARKS WILL BE LOST ON UPGRADE

keymap("User overrides - GenTerms", {
    C("Alt-Tab"):               C("Alt-Tab"),                   # Allow Option+Tab usage in terminals
}, when = lambda ctx:
    cnfg.screen_has_focus and
    matchProps(clas=termStr)(ctx)
)

###  SLICE_MARK_END: user_apps  ###  EDITS OUTSIDE THESE MARKS WILL BE LOST ON UPGRADE
###################################################################################################
```

As for why your virtualized `Option+Backspace` wouldn't be working as expected in `neovim`, that is a little less straightforward. There's this stuff in the general terminals keymap: 

```py
# Active in all apps in the terminals list
keymap("General Terminals", {

    ### wordwise overrides of general GUI block
    C("Alt-Backspace"):         C("Alt-Shift-Backspace"),       # Wordwise delete word left of cursor in terminals
    C("Alt-Delete"):           [C("Esc"),C("d")],               # Wordwise delete word right of cursor in terminals
    C("RC-Backspace"):          C("C-u"),                       # Wordwise delete line left of cursor in terminals
    C("RC-Delete"):             C("C-k"),                       # Wordwise delete line right of cursor in terminals
...
```

So, the virtualized shortcut sends `Alt+Shift+Backspace`. You might need to have a shortcut redirect in your `neovim` config to delete word when it receives `Alt+Shift+Backspace`? 

That shortcut should be doing the expected word deletion in all terminals, and WezTerm is on the list of terminals, so you wouldn't necessarily want to try to override that in your Toshy config file. 

I'm actually a bit confused about why it wouldn't be doing delete word in `neovim` as well. It works in my local install of WezTerm, but I'm not a `vim` user of any kind, so I don't know how that works.

**Comment by hugegulp** [comment]
@RedBearAK Interesting! This has helped a lot. I figured there'd be some weirdness with the alt+tab. I opted to map alt+shift+tab to the neovim function then mapped my physical alt+tab press to alt+shift+tab in terminals in toshy! This works well enough for my purposes. I added another mapping for alt+shift+backspace for word delete in neovim, and that solved my other issue too! I'll study the toshy config a bit more, there seems to be a lot here I can benefit from understanding deeper :pray:  thank you so much @RedBearAK this tool has been a godsend :heart:

**Comment by RedBearAK** [comment]
@hugegulp 

> opted to map alt+shift+tab to the neovim function then mapped my physical alt+tab press to alt+shift+tab in terminals in toshy

It's a good thing you were paying more attention than I was. Obviously allowing `Alt+Tab` to be `Alt+Tab` like I suggested would just cause task switching away from the terminal window. Good work redirecting it to `Alt+Shift+Tab`. Although, actually that should have resulted in reverse task switching away from the terminal window... ? Not sure why it wouldn't. Might depend on the desktop environment. Anyway, if it works, it works. 

There are quite a few Wiki pages now, talking about specific things, and of course the FAQ and README are both still pretty long. But if you have a question that is not apparently addressed directly there, or any other problem, open new issues whenever. 

> this tool has been a godsend

Don't I know it. I use it every day, on every Linux machine I have to mess with for more than an hour. Thank goodness for Kinto's existence so that I could base Toshy around its excellent config file. And the work the `keyszer` dev did to fix `xkeysnail` issues. There has been a lot of standing on shoulders to get this working as well as it does.
