### ISSUE TITLE
(Question) Holding control + key only respond once

### ISSUE THREAD

**Issue by ziwei-jiang** [RedBearAK/toshy#393]
Hi, 

Is there any way to make the control + key work when holding the keys?

For example, the cursor is expecting to move backward when holding control + b, but now it only responds once and I have to click it multiple times.

Thanks.

**Comment by RedBearAK** [comment]
@ziwei-jiang 

I modified the keymapper some time ago to ignore "repeat" key events, to overcome the fact that it was using too much CPU for some users while gaming. 

Fortunately I also left a way to re-enable the processing of repeating key events, which should fix your problem. 

I'm guessing this is the remapped shortcut that is causing the problem, because it only affects shortcuts that get remapped in the config file. Modifiers get moved around, so the "Super" here is actually the physical Ctrl key location while using a non-terminal application, so don't be confused by that. 

```py
    # emacs style
    C("Super-a"):               C("Home"),                      # Beginning of Line
    C("Super-e"):               C("End"),                       # End of Line
    C("Super-b"):               C("Left"),
    C("Super-f"):               C("Right"),
    C("Super-n"):               C("Down"),
    C("Super-p"):               C("Up"),
    C("Super-k"):              [C("Shift-End"), C("Backspace")],
    C("Super-d"):               C("Delete"),
```

I'm afraid I don't use these types of shortcuts, so I didn't realize these would probably be affected by stopping the keymapper from processing the "repeat" key events. 

Open the config file in a text/code editor. The file is here: 

```
~/.config/toshy/toshy_config.py
```

And there is a menu item in the tray icon menu to quickly open the config folder, if you find that convenient. 

Find this section tagged with `keymapper_api` in your `toshy_config.py` near the top: 

```py
###################################################################################################
###  SLICE_MARK_START: keymapper_api  ###  EDITS OUTSIDE THESE MARKS WILL BE LOST ON UPGRADE

# Keymapper-specific config settings - REMOVE OR SET TO DEFAULTS FOR DISTRIBUTION
dump_diagnostics_key(Key.F15)   # default key: F15
emergency_eject_key(Key.F16)    # default key: F16

timeouts(
    multipurpose        = 1,        # default: 1 sec
    suspend             = 1,        # default: 1 sec, try 0.1 sec for touchpads/trackpads
)

# Delays often needed for Wayland and/or virtual machines or slow systems
throttle_delays(
    key_pre_delay_ms    = 12,      # default: 0 ms, range: 0-150 ms, suggested: 1-50 ms
    key_post_delay_ms   = 18,      # default: 0 ms, range: 0-150 ms, suggested: 1-100 ms
)

devices_api(
    # Only the specified devices will be "grabbed" and watched for during 
    # device connections/disconnections. 
    only_devices = [
        # 'Example Disconnected Keyboard',
        # 'Example Connected Keyboard',
    ]
)

###  SLICE_MARK_END: keymapper_api  ###  EDITS OUTSIDE THESE MARKS WILL BE LOST ON UPGRADE
###################################################################################################
```

Anywhere inside these "slice marks", add this function call, which should disable the "ignoring" behavior: 

```py
ignore_repeating_keys(False)
```

Save the file, and use the tray icon menu to restart the Toshy services, or use this command in the terminal: 

```
toshy-services-restart
```

If anything seems to be going wrong, you can see verbose debugging output with this: 

```
toshy-debug
```

Using that API call, you should find that the normal repeating behavior is back. If you are a gamer, you may want to comment that out and restart Toshy, or even disable Toshy, while gaming. Because repeatedly remapping a shortcut to something else does tend to use up most of a CPU core (or thread) for as long as you're holding the repeating remapped key or combo. How noticeable this is depends on how many cores you have, and how powerful the CPU is overall. 

If you used the `toshy-debug` command, Toshy can be reverted to normal background operation by just restarting the Toshy services from the tray icon menu again. Or, the process can be stopped with `Ctrl+C` or (if everything is working correctly) `Cmd+Dot`. But if the terminal is not being recognized correctly as a terminal, the `Ctrl+C` might actually be on physical `Cmd+C` (Apple keyboard) or `Alt+C` (PC keyboard) due to the modifier remapping. 

Let me know if any of this is too confusing or doesn't work for you.

**Comment by RedBearAK** [comment]
In testing, I only see the keymapper using at most 0.6% CPU while holding the `Ctrl+B` shortcut, on my Ryzen 3700u 4c/8t laptop CPU. That's actually a lot less than I was expecting. Looks like my other major optimizations of the config file have helped a lot, compared to the state it was in a few months ago. 

But if you hold the shortcut for long enough, you still may see something that was also one of the reasons I disabled the processing of repeating keys: Buffering. The remapped repeating key events might continue briefly after you let go, depending on how fast your CPU is, or how busy your system is, and how long you hold the keys down. 

Just letting you know. The keymapper simply isn't fast enough to completely get rid of this buffering phenomenon in all cases. I've minimized the issue as much as I can. It should be usable in most cases. There should be no detectable buffering when the keymapper is NOT being asked to remap the repeating key events onto something else.

**Comment by ziwei-jiang** [comment]
Thank you very much for looking into this and your timely response! I have tried the solution you suggested and it works well for me.
Cheers!

**Comment by RedBearAK** [comment]
@ziwei-jiang 

I forgot to point out that if you run into the buffering problem, you can mitigate it pretty easily by slowing down the repeat rate of your keyboard. 

How you do that depends on your desktop environment. Or you may be able to do it from the terminal, with something like `kbdrate`, but the command would probably need to be added to a system-level environment script or `~/.profile`, to activate the same setting on every login session. 

There's a Wiki article that discusses some of the options. 

https://github.com/RedBearAK/toshy/wiki/Repeating-Keys-Settings
