### ISSUE TITLE
(Enh) xwaykeyz excessive logging when unlocking GNOME

### ISSUE THREAD

**Issue by phipolis** [RedBearAK/toshy#430]
**Is your feature request related to a problem? Please describe.**
Every time I return to my active Gnome session - that is screen locked and display sleep, but not suspend - xwaykeys prints huge numbers of log lines about dbus errors looking for the Gnome Shell extensions. Just now I got over 1000 in 3 seconds.

**Describe the solution you'd like**
The message says "Ignore this error if screen was locked/inactive at the time." and it was locked, so ideally there is a way to detect that. Or it could print the message once, or rate limit. Another possibility is remembering when the plugin has been seen previously in the session, and only showing the warning when the plugin has never been seen.

I also wonder if there's any DBus path that reliably exists on every Gnome installation but is likewise unavailable when the screen is locked. If there is, you could make a screen off test that way?

**Additional context**
Output of `journalctl` over the period: [xwaykeys.log](https://github.com/user-attachments/files/17580161/xwaykeys.log)

```
$ toshy-versions

File Name                        Version
-------------------------------------------
toshy_config.py                  2024.09.15
toshy_gui.py                     2024.09.15
toshy_tray.py                    2024.10.03

env_context.py                   2024.09.15
notification_manager.py          2024.09.15
settings_class.py                2024.09.15

toshy_cosmic_dbus_service.py     2024.10.14
toshy_kde_dbus_service.py        2024.10.16
toshy_wlroots_dbus_service.py    2024.09.04

$ toshy-env

(EV) Toshy env_info module sees this environment:
                 DISTRO_ID       = 'fedora'
                 DISTRO_VER      = '41'
                 VARIANT_ID      = 'workstation'
                 SESSION_TYPE    = 'wayland'
                 DESKTOP_ENV     = 'gnome'
                 DE_MAJ_VER      = '47'
                 WINDOW_MGR      = 'gnome-shell'
```

**Comment by RedBearAK** [comment]
@phipolis 

Typically each error block will print out for every character in your password as you unlock the screen. I am away from my computer for a few days. I’ll think about some ways of rate limiting without impacting performance or leaving the user uninformed about not having any compatible extensions enabled. 

The keymapper wasn’t designed to care about the session status. I have to monitor that using a separate service that periodically queries “loginctl” to be able to support multiple users on the same system. 

But I’m sure something can be done to make the GNOME extension errors less frequent.

**Comment by phipolis** [comment]
Thanks for the reply! Obviously this isn't a critical issue warranting a major change, but I still appreciate you pondering it. I hope you enjoy your time afk!

:thinking: ...although that does seem to mean it leaks the length of a user's password to the system logs... :sweat_smile:

**Comment by RedBearAK** [comment]
> leaks the length of a user's password to the system logs

I suppose you could say it would allow a guess, but any typos or other keyboard interaction would throw off the count. Might be a good idea to mildly randomize the fade-out/fade-in of the rate limiting. 

If you were doing a “switch user” kind of thing then the keymapper service is supposed to be stopped entirely, which would mean none of those errors would appear. I feel like the difficulty was detecting that the screen is locked rather than the session being “inactive” (I think “inactive” also applies to the screen being blanked). So I will have to take a look at a few different things. There must just be some basic way to check whether the GNOME shell is responsive or not. We’ll see.

**Comment by RedBearAK** [comment]
@phipolis 

I put in some rate limiting of the main error message block. Right now it's only in the `dev_beta` branch of `xwaykeyz`, which means in order to try it you'd need to edit this line in `setup_toshy.py`: 

```py
        self.keymapper_branch       = 'main'          # new branch when switched to 'xwaykeyz'
```

And make it look like this (and then run the installer):

```py
        self.keymapper_branch       = 'dev_beta'          # new branch when switched to 'xwaykeyz'
```

After I merge it into the main branch of `xwaykeyz`, everyone will be getting it on new Toshy installs. It will show v1.3.2 in the journal after restarting the services (the services have to be restarted twice to see the version line, for some reason). 

The individual error messages about each extension not being found will now only show up in the verbose debugging output (not the journal). Such as when you use `toshy-debug` in the terminal. 

In the journal, the main error block will come out once for every 12-17 key events, a semi-randomized interval. There should be no concerns about leaking any kind of accurate number of keystrokes or password length info.

**Comment by RedBearAK** [comment]
Change was merged into the main branch of `xwaykeyz`. That should take care of this from now on.
