### ISSUE TITLE
(Question) How do I map map my `cmd+1`, `cmd+2`, etc to `alt+x` in terminals?

### ISSUE THREAD

**Issue by englut** [RedBearAK/toshy#441]
I'm trying to map my `cmd+1`, `cmd+2`, etc to `alt+x` so I can switch tabs in my wezterm. But the global `meta+1`, `meta+2`, etc shortcuts are taking precedence instead.

```
keymap("User overrides - GenTerms", {
    C("Super-1"):               C("Alt-1"),
    C("Super-2"):               C("Alt-2"),
    C("Super-3"):               C("Alt-3"),
    C("Super-4"):               C("Alt-4"),
    C("Super-5"):               C("Alt-5"),
    C("Super-6"):               C("Alt-6"),
    C("Super-7"):               C("Alt-7"),
    C("Super-8"):               C("Alt-8"),
    C("Super-9"):               C("Alt-9"),
    C("Super-0"):               C("Alt-0"),
}, when = lambda ctx:
    cnfg.screen_has_focus and
    matchProps(clas=termStr)(ctx)
)
```

I know in firefox and other browers the `Super` modifier is able to be captured as expected. So I tried to use a similar keymap:

```
keymap("User overrides - GenTerms", {
    C("RC-Key_1"):               C("Alt-1"),
    C("RC-Key_2"):               C("Alt-2"),
    C("RC-Key_3"):               C("Alt-3"),
    C("RC-Key_4"):               C("Alt-4"),
    C("RC-Key_5"):               C("Alt-5"),
    C("RC-Key_6"):               C("Alt-6"),
    C("RC-Key_7"):               C("Alt-7"),
    C("RC-Key_8"):               C("Alt-8"),
    C("RC-Key_9"):               C("Alt-9"),
    C("RC-Key_0"):               C("Alt-0"),
}, when = matchProps(clas=termStr))
```

None of these work, what's the correct way to get this working?

Also, `cmd`/`super`/`meta` is used interchangeably.... what does `RC-` mean?

**Comment by RedBearAK** [comment]
@englut 

I'm going to try to clear up things one piece at a time so that you can get to the result you want, and understand how it works. (And because I'm still easily confused too. There's a lot of redirection going on.)

- The basic modifier remap is different between "GUI" applications and "terminals". And there are different modmaps that try to "normalize" different keyboard types so they all work the same when you're setting up remaps. 
- While Meta/Super/Win/Cmd all technically refer to the same key code, that key code disappears in terminals. So you can't use it in remaps in terminal apps. 
- The virtualized "Command" key is actually `RIGHT_CTRL`, so where you see `RC` on the "input" side of any remap, that is a representation of the key that is acting like the `Cmd` key. In GUI apps the Meta/Super/Win/Cmd key code shifts over to the physical Ctrl key, except in terminals, where that key remains `LEFT_CTRL`, and there is no Meta/Super/Win/Cmd key code. 
- You don't need to use the `Key_N` notation anymore for number keys, since `keyszer` was forked from `xkeysnail` (and the current keymapper `xwaykeyz` is just a renamed fork of `keyszer`). 

Now, if those `Alt+N` number shortcuts work, they should technically already be working from the virtualized Option key (which is whatever key is two keys away from the Space bar, regardless of the keyboard type). Do they work from that key? 

Do the original `Alt+N` number shortcuts work from the physical `Alt` key if Toshy is disabled from the tray icon? 

Are you restarting Toshy after editing and saving the changes to the config file? (I'm sure you are.)

Technically your second keymap example should be doing the job, I think, if you're trying to get the physical equivalent of `Cmd+N` number shortcuts to switch the tabs. 

You're doing a great job understanding how to put the conditional `when` expressions together. Although I might actually try restricting the conditional to just making the keymap active in WezTerm until you can confirm those `Alt+N` number shortcuts work in other terminal apps. 

The global Meta/Super shortcuts taking precedence kind of depends on the desktop environment/shell. But that key code is not available in terminals, so the first set of remaps should have just... not worked in terminals at all. 

Not really sure what's going on without more information.

**Comment by englut** [comment]
Thanks for this long detailed response, I really appreciate you putting in the time and effort in supporting your users, especially after spending so much time and effort coding this awesome tool :heart: 

>     * The basic modifier remap is different between "GUI" applications and "terminals". And there are different modmaps that try to "normalize" different keyboard types so they all work the same when you're setting up remaps.
> 
>     * While Meta/Super/Win/Cmd all technically refer to the same key code, that key code disappears in terminals. So you can't use it in remaps in terminal apps.

Ah this is interesting. That makes sense why `Super` doesn't work. 

>     * The virtualized "Command" key is actually `RIGHT_CTRL`, so where you see `RC` on the "input" side of any remap, that is a representation of the key that is acting like the `Cmd` key. In GUI apps the Meta/Super/Win/Cmd key code shifts over to the physical Ctrl key, except in terminals, where that key remains `LEFT_CTRL`, and there is no Meta/Super/Win/Cmd key code.
> 
> Now, if those `Alt+N` number shortcuts work, they should technically already be working from the virtualized Option key (which is whatever key is two keys away from the Space bar, regardless of the keyboard type). Do they work from that key?

Fascinating, this is making me rethink how I should map those keys in general now. 

And yes! In my `konsole`, `wezterm`, `yakuake`, etc, they all respond to `alt+x` as I would expect. But the `cmd+x` keys don't work. 

> Do the original `Alt+N` number shortcuts work from the physical `Alt` key if Toshy is disabled from the tray icon?
Yes they do :pray: 

> Are you restarting Toshy after editing and saving the changes to the config file? (I'm sure you are.)

:100: Good question to ask and cross off the list :saluting_face: 
 
> Technically your second keymap example should be doing the job, I think, if you're trying to get the physical equivalent of `Cmd+N` number shortcuts to switch the tabs.
> 
> You're doing a great job understanding how to put the conditional `when` expressions together. Although I might actually try restricting the conditional to just making the keymap active in WezTerm until you can confirm those `Alt+N` number shortcuts work in other terminal apps.

Thank you! I figured I'd remove the focus condition for now and get it working before honing it in after. The `alt+N` shortcuts work with the other terminals I mentioned, and the same `cmd+N` shortcuts fail also.

> The global Meta/Super shortcuts taking precedence kind of depends on the desktop environment/shell. But that key code is not available in terminals, so the first set of remaps should have just... not worked in terminals at all.
> 
> Not really sure what's going on without more information.

Hmmmm... this is very interesting. Thank you for all this info, it's make much more sense to me now. I had also had `CTRL-N` remaps in combination with the `RC-N` remaps.. and I bet that there were conflicts!

Now knowing that what `RC` and `LC` meant in terms of `Meta`/`Super`, I am using the following, and things are working the way I desired!

```
keymap("User overrides - GenTerms", {
    C("RC-1"):              C("Alt-1"),
    C("RC-2"):              C("Alt-2"),
    C("RC-3"):              C("Alt-3"),
    C("RC-4"):              C("Alt-4"),
    C("RC-5"):              C("Alt-5"),
    C("RC-6"):              C("Alt-6"),
    C("RC-7"):              C("Alt-7"),
    C("RC-8"):              C("Alt-8"),
    C("RC-9"):              C("Alt-9"),
    C("LC-1"):              C("Meta-1"),
    C("LC-2"):              C("Meta-2"),
    C("LC-3"):              C("Meta-3"),
    C("LC-4"):              C("Meta-4"),
    C("LC-5"):              C("Meta-5"),
    C("LC-6"):              C("Meta-6"),
    C("LC-7"):              C("Meta-7"),
    C("LC-8"):              C("Meta-8"),
    C("LC-9"):              C("Meta-9"),
    C("LC-0"):              C("Meta-0"),
}, when = matchProps(clas=termStr))
```

Thank you so much for your help @RedBearAK you really are a rockstar :heart_eyes:

**Comment by RedBearAK** [comment]
@englut 

> I had also had CTRL-N remaps in combination with the RC-N remaps.. and I bet that there were conflicts!

If they were active at the same time, and the `Ctrl-N` shortcuts were encountered first in memory, yes. One of them would mask the other remap. And you generally want to differentiate between `LC` and `RC` in the Toshy config (for "input" shortcuts, not "output" shortcuts), for obvious reasons. 

The solution you found looks good. I'm guessing the remaps from `LC` onto `Meta` shortcuts are for workspaces or something. (That kind of thing is difficult to safely universalize between different desktop environments.)

I do hope you're putting your custom keymaps in the `user_apps` slice, so they will survive a Toshy reinstall. I assume you are, based on the name you gave the keymap. 

If these numbered tab shortcuts are really something that applies to a lot of Linux terminals, and also mimic shortcuts that work in some Mac terminal apps like iTerm2 or Terminal.app, I might need to think about adding them to the default Toshy config file. I'll take a look at how the Mac terminals behave. Gotta be really careful about adding new default remaps. 

> Thank you so much for your help @RedBearAK you really are a rockstar 😍

If that were true I'd be able to solve all the remaining complicated problems with the keymapper, like supporting international keyboard layouts much better. 💀 But thanks anyway. 😸 

Good work.

**Comment by englut** [comment]
Yes! For sure, I put all that in the user apps section. Even did an upgraded yesterday so it was all carried over :saluting_face: 

Yeah, I'm using ctrl+N for switching virtual desktops (which I was using on macOS too) and cmd+N for tab switching. It could be something that's global for terminals, the tab switching at least. 

You're definitely a rock star. International keyboards are always another beast!
