### ISSUE TITLE
(Question) Ubuntu Keymaps Don't Work (?)

### ISSUE THREAD

**Issue by assafdori** [RedBearAK/toshy#469]
Hey,

First, thank you for creating this tool.

I was using it on PopOS without any issues at all, but I had to move to plain Ubuntu due to work decisions.

On plain Ubuntu, the CMD and CTRL buttons didn't switch. What I mean by that is that I still have to use CTRL+A for example to select all text, instead of CMD+A. Or another example is I can't paste using CMD+V.

It really worked like wonder on PopOS, but no luck on Ubuntu.

I tried re-installing, re-booting, re-starting Toshy service & config, no luck.

Did I miss anything?

```
The active init system is: 'systemd' (Systemd)

(EV) Toshy installer sees this environment:
	DISTRO_ID        = 'ubuntu'
	DISTRO_VER       = '24.04'
	VARIANT_ID       = 'notfound'
	SESSION_TYPE     = 'wayland'
	DESKTOP_ENV      = 'gnome'
	DE_MAJ_VER       = '46'
	WINDOW_MGR       = 'gnome-shell'
```

**Comment by assafdori** [comment]
I was able to resolve this issue by making sure when I log in to Ubuntu to choose X11 / Xorg instead of Wayland.

Thank you @RedBearAK for your work.

**Comment by RedBearAK** [comment]
> I was able to resolve this issue by making sure when I log in to Ubuntu to choose X11 / Xorg instead of Wayland.
> 
> Thank you @RedBearAK for your work.

Any GNOME Wayland session requires installing one (or more, if you want) of the GNOME shell extensions found in the "Requirements" section of the README. You were probably only using X11/Xorg on Pop, which is why you didn't notice this before. 

The README also describes how to install the "Extension Manager" app from Flathub, which is the easiest way to deal with extensions. 

The extension website was down last night. Hopefully it's back now.

**Comment by RedBearAK** [comment]
I'm going to close this as resolved since there are two different known solutions already documented (using an X11/Xorg session and/or installing a recommended GNOME shell extension to support the Wayland session). 

Open a new issue if anything else comes up. 👍🏽
