### ISSUE TITLE
[BUG] Logitech MX Master 3 Mouse Side Buttons Blocked

### ISSUE THREAD

**Issue by alexmarder** [RedBearAK/toshy#7]
```
Bare metal or virtual machine: Bare metal
(If in VM, which VM software): None

(Try running 'toshy-env' in a terminal.)

Linux distro name: Ubuntu
Distro version: 23.04
X11/Xorg or Wayland: X11 
Desktop environment(s): Gnome

DE(s) tried with Wayland?: No
```

These terminal commands may provide helpful info:

- toshy-services-log  
- toshy-services-status  
- toshy-config-start-verbose  

Problem observed:  
* * *
The Logitech MX Master 3 presents the side buttons as a keyboard. Toshy seems to prevent them from doing anything.

Toshy disabled: side buttons (BTN_SIDE 1685540094.3731189 and BTN_SIDE 1685540094.474581) navigate forward and backward in Firefox.
Toshy enabled: side buttons do nothing.

Thank you so much for your incredible effort!

**Comment by RedBearAK** [comment]
@alexmarder 

> Thank you so much for your incredible effort!

Very kind of you to say. We're halfway to something usable already.  🤣 

> side buttons (BTN_SIDE 1685540094.3731189 and BTN_SIDE 1685540094.474581) navigate forward and backward in Firefox

I think this has something to do with the way that the keymapper `keyszer` is auto-grabbing whatever it thinks is a "keyboard" type device, which it bases on certain keyboard-like "capabilities" the device advertises. And when it gets "grabbed" keyszer blocks most `BTN_` outputs. So I'm not sure what I can immediately do about this on my side. My installer basically just sets up a very particular config file with `modmaps` and `keymaps` and `keyszer` takes care of the actual work. 

There were some plans to add some API functions to `keyszer` to add or remove specific devices that were either being inappropriately grabbed or weren't being seen as keyboards for some reason. But I don't think that has been implemented yet. 

Meanwhile, if you want to try some variations of the `keyszer` command you'll need to do what all the `toshy-*` command scripts do internally and "activate" the Python virtual environment where `keyszer` is installed. Troubleshooting should be done in a spare terminal window or tab that you can close in case `Ctrl+C` and `Cmd+Dot` fail to stop the process when you're done. Although if your Toshy tray icon is working, you should also be able to theoretically stop the process with the "Stop Toshy Script" item in the tray icon menu. 

```sh
source "$HOME/.config/toshy/.venv/bin/activate"
```

As long as you stay in the same "shell" instance after running this command, you should be able to use `keyszer` as if it was installed system-wide or in your ~/.local/bin (even though it isn't). 

You can see the device list (I need to make a script "command" for this) with this command: 

```sh
keyszer --list-devices
```

Now if we run the actual command from `toshy-config-start-verbose` you should start seeing the same logging output you would get from that "command". But in this case you can choose to change the options you give it. 

```sh
keyszer --flush -w -v -c "$HOME/.config/toshy/toshy_config.py"
```

The `--flush` is to stop some terminals from "buffering" the logging output so that it doesn't immediately come out when you mess with the keyboard. It's optional, if your terminal doesn't demonstrate that strange behavior. 

The `-w` gets `keyszer` to watch for the connect/disconnect events from plugging/unplugging a USB device. You may want to disable that. 

If you know which device from the device list is your actual keyboard, you can then pass it to `keyszer` without the `-w` flag with this: 

```sh
keyszer -v --add-device "keyboard device name" -c "$HOME/.config/toshy/toshy_config.py"
```

If that gets you a working "Toshy" situation where the keyboard works as expected but the side buttons on the mouse are no longer blocked, we can look at this further. I'm not actually sure about the syntax there, so double-check the `keyszer` README if that doesn't work. 

https://github.com/joshgoebel/keyszer

**Comment by RedBearAK** [comment]
@alexmarder 

> side buttons (BTN_SIDE 1685540094.3731189 and BTN_SIDE 1685540094.474581) navigate forward and backward in Firefox

AFAIK, the numbers that go along with those events are just timestamps, so there must be some other `evdev` events associated with what the side buttons normally do. If you run `evtest` (when `keyszer` is not running) you should see multiple events when using those buttons. It's possible those events should be getting passed through by `keyszer`, in which case the fix wouldn't necessarily be very complicated.

**Comment by alexmarder** [comment]
Here's the output from running evtest and pressing the buttons:
```
Event: time 1685678246.363700, -------------- SYN_REPORT ------------
Event: time 1685678250.383757, type 4 (EV_MSC), code 4 (MSC_SCAN), value 90004
Event: time 1685678250.383757, type 1 (EV_KEY), code 275 (BTN_SIDE), value 1
Event: time 1685678250.383757, -------------- SYN_REPORT ------------
Event: time 1685678250.561755, type 4 (EV_MSC), code 4 (MSC_SCAN), value 90004
Event: time 1685678250.561755, type 1 (EV_KEY), code 275 (BTN_SIDE), value 0
Event: time 1685678250.561755, -------------- SYN_REPORT ------------
Event: time 1685678251.923778, type 4 (EV_MSC), code 4 (MSC_SCAN), value 90005
Event: time 1685678251.923778, type 1 (EV_KEY), code 276 (BTN_EXTRA), value 1
Event: time 1685678251.923778, -------------- SYN_REPORT ------------
Event: time 1685678252.075776, type 4 (EV_MSC), code 4 (MSC_SCAN), value 90005
Event: time 1685678252.075776, type 1 (EV_KEY), code 276 (BTN_EXTRA), value 0
Event: time 1685678252.075776, -------------- SYN_REPORT ------------
```

**Comment by RedBearAK** [comment]
@alexmarder 

So that's event codes 275 and 276. Wonder what happens if we add them to the list of mouse buttons that are already being passed through by `keyszer` in the `output.py` file. 

```py
_MOUSE_BUTTONS = {
    256: ["BTN_0", "BTN_MISC"],
    257: "BTN_1",
    258: "BTN_2",
    259: "BTN_3",
    260: "BTN_4",
    261: "BTN_5",
    262: "BTN_6",
    263: "BTN_7",
    264: "BTN_8",
    265: "BTN_9",
    272: ["BTN_LEFT", "BTN_MOUSE"],
    274: "BTN_MIDDLE",
    273: "BTN_RIGHT",
}
```

You can edit the file by running this in the terminal: 

```sh
cd ~/.config/toshy
nano $(find . -name output.py)
```

Use `Ctrl+X` to exit and choose to save the buffer when you're done editing (just in case you've never used `nano` before). 

Add these lines at the end of the list above. You'll find it near the beginning of the file that should have opened in `nano`.  

```py
    275: "BTN_SIDE",
    276: "BTN_EXTRA",
```

When you get it saved, restart the Toshy services or run the manual command in the terminal (toshy-config-start-verbose) and see what happens with the mouse side buttons. You should be running with the modified version of `keyszer` that theoretically won't block those events from the mouse device. 

Not quite as good as keeping `keyszer` from grabbing the mouse, but it might work.

**Comment by RedBearAK** [comment]
@alexmarder 

Thanks for taking the time to test that idea. 

This might actually be the better solution, since I think having the mouse device grabbed will help get Mod+click events through the `keyszer` "suspend" timeout that tries to stop issues like the `Alt` key focusing menus in Firefox and VSCode. 

I'm going to keep this issue open in case others have a similar issue, and as a reminder to submit a PR to `keyszer`. 

If you re-run the Toshy installer at some point you'll need to re-apply the fix, until it gets incorporated into either my development branch or mainline `keyszer`. I re-clone the `keyszer` branch and re-intitialize the Python virtual environment location where it gets installed every time the Toshy installer is run, to make sure the installed version of `keyszer` has all expected features.

**Comment by RedBearAK** [comment]
Man, I just realized that I didn't read the initial post thoroughly enough. This is literally a fancy keyboard we are talking about, not a separate "mouse" device. One of the infamous Logitech MX Master keyboards. 

@alexmarder can you confirm this is just one device we are talking about? A keyboard with extra mouse-like buttons? In which case the idea of not grabbing the device was irrelevant to the situation. 🤦🏽 

Changed the issue title to reflect the understanding I got from re-reading the initial post.

**Comment by RedBearAK** [comment]
@alexmarder 

Looks like the fix was simple enough that the `keyszer` dev decided to merge it already. That means I can include it in my development branch of `keyszer` without causing any confusion moving forward. Once I do that, you'll be able to install or re-install Toshy without losing the fix. 👍

**Comment by RedBearAK** [comment]
@alexmarder 

Toshy should now be installing a copy of `keyszer` with the fix for this issue integrated. 

Closing issue as completed.
