### ISSUE TITLE
(Enh) Hyprland support

### ISSUE THREAD

**Issue by fecet** [RedBearAK/toshy#86]
leave blank now as I have to reboot to hyprland later

**Comment by RedBearAK** [comment]
Can you check the output from these commands when you get a chance (no hurry): 

```sh
echo $XDG_CURRENT_DESKTOP
```

```sh
echo $XDG_SESSION_DESKTOP
```

```sh
ps aux | grep -i hypr
```

**Comment by RedBearAK** [comment]
Very helpful, thanks. 

Do you get anything from this? Again, no hurry. 

```sh
echo $HYPRLAND_INSTANCE_SIGNATURE
```

**Comment by fecet** [comment]
Yes, I get
```
0a78f6031c8fcc6773f136fccde3d560aaac239d_1693962151
```

**Comment by RedBearAK** [comment]
OK, good. In theory I have a version of Toshy that could work. 

If you want to test this, I think it has about a 50/50 chance of working. 

[toshy-dev_beta_hyprland_test.zip](https://github.com/RedBearAK/toshy/files/12530129/toshy-dev_beta_hyprland_test.zip)

If you don't want the Mac-like keyboard shortcuts that Toshy normally does, use this installer option: 

```sh
./toshy_setup.py --barebones-config
```

(You should only need to use that option once, the installer is designed to notice if you have an existing barebones config file and avoid replacing it with the default Toshy config. This is important to know, since you may need to repeat the install a few times if I need to fix things.)

It will probably ask you to reboot, if the installer finishes without an error. Before rebooting, you might want to run this command so that it doesn't start automatically at boot: 

```sh
~/.local/bin/toshy-services-disable
```

If you close the terminal and open a new one you should be able to just use it like any other command, because it should be available in the PATH: 

```sh
toshy-services-disable
```

Then reboot, and you can manually run the verbose command first to see what kind of errors show up in the logging. 

```sh
toshy-config-verbose-start
```

Most of the time you can stop it with Ctrl+C, but on some systems you may need to close the terminal window or tab to kill the process, or set the emergency eject key to kill the keymapper. You'll find it near the beginning of the `toshy_config.py` file: 

```py
# Keyszer-specific config settings - REMOVE OR SET TO DEFAULTS FOR DISTRIBUTION
dump_diagnostics_key(Key.F7)   # default key: F15
emergency_eject_key(Key.F8)    # default key: F16
```

It needs to be a single key on your keyboard somewhere. Default is F16 but I have mine set to F8 as shown here, because there's no other function on that key on my laptop. 

You should also be able to stop the script from the tray icon menu, with the "Stop Toshy Script" option. 

This command should show Toshy detecting Wayland as the session type and Hyprland as the desktop environment. 

```sh
toshy-env
```

If this command is showing the wrong info the Toshy config file will tell the keymapper to use the wrong code to grab the window context. That can be manually overridden in the config file, but it would be better to fix the environment detection module if that happens. 

Whether we can get this to work will mostly be up to your ability to spend time testing it.

**Comment by RedBearAK** [comment]
@fecet 

Updated test version for Hyprland: 

[toshy-dev_beta_hyprland_2023-09-09.zip](https://github.com/RedBearAK/toshy/files/12565317/toshy-dev_beta_hyprland_2023-09-09.zip)

**Comment by fecet** [comment]
Thank you for your hard work and sorry for late. I'm currently in a somewhat awkward situation because I can't configure my dotfiles in an environment without a keymap I'm familiar with. Without doing so, I can't make the Wayland environment feel familiar to me. 
This weekend, I finally managed to set up a functional Hyprland environment, and I'll be trying out your program soon.

**Comment by RedBearAK** [comment]
No problem. I think you mean "sorry for the late reply." I'm hopeful that the code will work right away. There are actually three different methods now that it can cascade through, so I'm interested to see what happens. 

Maybe you can copy the output from the verbose command into a text file and attach it here, so I can see what you encounter when trying it. 

```sh
mkdir -p ~/Documents/Toshy_logs
toshy-config-verbose-start | tee ~/Documents/Toshy_logs/toshy_verbose_log_$(date +%Y%m%d_%H%M%S).txt
```

Each time you run that second command it should produce a new timestamped output file in a "Toshy_logs" folder in your Documents folder, which you can then attach to a comment here. Adjust the path if you want the files to be saved somewhere else. 

Using `tee` will of course allow the output to also show in the terminal as you use the keyboard. 

You can make a shorter way to run this entire command by adding this Bash function to your shell's RC file: 

```sh
toshy-verbose-log() {
    mkdir -p "${HOME}/Documents/Toshy_logs"
    filename="${HOME}/Documents/Toshy_logs/toshy_verbose_log_$(date +%Y%m%d_%H%M%S).txt"
    toshy-config-verbose-start | tee "${filename}"
}
```

For the Bash shell the RC file is `~/.bashrc`, put the Bash function at the end of the file and restart the terminal. Then you should be able to create logging files by just running this command: 

```sh
toshy-verbose-log
```

> [WARNING!]
> Be aware that this is truly verbose logging of keyboard input. Don't type any passwords while using the verbose logging, or don't post the file here if you think it might contain a password or some other secret info!

I advise you to use the verbose logging to a file only for brief runs to help determine if Toshy is working. Do some basic things like switching applications, opening and closing tabs in the terminal or a browser. Try the sample remaps in the barebones config file: 

```py
# Example keymap that adds British Pound and Euro symbols to any keyboard layout.
keymap("Currency character overlay", {
    C("RAlt-Key_4"):            UC(0x00A3),                     # £ British Pound currency symbol
    C("RAlt-Key_5"):            UC(0x20AC),                     # € Euro currency symbol
}, when = lambda _: True is True)
```

More info will show up in the verbose logging when using these sample remaps. Or any other remaps that you add yourself. Note that these remaps use `RAlt`, which means you need to use the Alt key on the right side of the keyboard.

**Comment by RedBearAK** [comment]
I was able to test this and fix some issues. Current main should work on Hyprland, but some global shortcuts will probably need to be tweaked if you are not using the JaKooLit script to set up Hyprland on Fedora. 

Closing as complete.
